### ISSUE TITLE
Make sure the app works on MS Edge

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#105]

**Comment by ricschuster** [comment]
Taking screenshot creates errors:

Access to XMLHttpRequest at 'https://stamen-tiles-b.a.ssl.fastly.net/toner/8/71/90@2x.png' from origin 'https://ncc.carleton.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
VM210:1 cannot fetch resource: https://stamen-tiles-b.a.ssl.fastly.net/toner/8/71/90@2x.png, status: 0
r @ VM210:1
i @ VM210:1
XMLHttpRequest.send (async)
(anonymous) @ VM210:1
l @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
d @ VM210:1
Promise.then (async)
n @ VM210:1
l @ VM210:1
o @ VM210:1
_createImagePlaceholder @ VM210:1
printMap @ VM210:1
(anonymous) @ VM211:31
LeafletWidget.methods.easyprintMap @ VM211:33
(anonymous) @ leaflet.js:854
_sendMessagesToHandlers @ shinyapp.js:529
(anonymous) @ shinyapp.js:641
_sendMessagesToHandlers @ shinyapp.js:529
dispatchMessage @ shinyapp.js:515
n.onmessage @ shinyapp.js:112
VM210:1 GET https://stamen-tiles-b.a.ssl.fastly.net/toner/8/71/90@2x.png net::ERR_FAILED
(anonymous) @ VM210:1
l @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
d @ VM210:1
Promise.then (async)
n @ VM210:1
l @ VM210:1
o @ VM210:1
_createImagePlaceholder @ VM210:1
printMap @ VM210:1
(anonymous) @ VM211:31
LeafletWidget.methods.easyprintMap @ VM211:33
(anonymous) @ leaflet.js:854
_sendMessagesToHandlers @ shinyapp.js:529
(anonymous) @ shinyapp.js:641
_sendMessagesToHandlers @ shinyapp.js:529
dispatchMessage @ shinyapp.js:515
n.onmessage @ shinyapp.js:112
ncc.carleton.ca/:1 Access to XMLHttpRequest at 'https://stamen-tiles-a.a.ssl.fastly.net/toner/8/74/90@2x.png' from origin 'https://ncc.carleton.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
VM210:1 cannot fetch resource: https://stamen-tiles-a.a.ssl.fastly.net/toner/8/74/90@2x.png, status: 0
r @ VM210:1
i @ VM210:1
XMLHttpRequest.send (async)
(anonymous) @ VM210:1
l @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
d @ VM210:1
Promise.then (async)
n @ VM210:1
l @ VM210:1
o @ VM210:1
_createImagePlaceholder @ VM210:1
printMap @ VM210:1
(anonymous) @ VM211:31
LeafletWidget.methods.easyprintMap @ VM211:33
(anonymous) @ leaflet.js:854
_sendMessagesToHandlers @ shinyapp.js:529
(anonymous) @ shinyapp.js:641
_sendMessagesToHandlers @ shinyapp.js:529
dispatchMessage @ shinyapp.js:515
n.onmessage @ shinyapp.js:112
VM210:1 GET https://stamen-tiles-a.a.ssl.fastly.net/toner/8/74/90@2x.png net::ERR_FAILED
(anonymous) @ VM210:1
l @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
(anonymous) @ VM210:1
(anonymous) @ VM210:1
Promise.then (async)
e @ VM210:1
d @ VM210:1
Promise.then (async)
n @ VM210:1
l @ VM210:1
o @ VM210:1
_createImagePlaceholder @ VM210:1
printMap @ VM210:1
(anonymous) @ VM211:31
LeafletWidget.methods.easyprintMap @ VM211:33
(anonymous) @ leaflet.js:854
_sendMessagesToHandlers @ shinyapp.js:529
(anonymous) @ shinyapp.js:641
_sendMessagesToHandlers @ shinyapp.js:529
dispatchMessage @ shinyapp.js:515
n.onmessage @ shinyapp.js:112
VM210:1 oops, something went wrong! Event {isTrusted: true, type: "error", target: img.leaflet-tile.leaflet-tile-loaded, currentTarget: img.leaflet-tile.leaflet-tile-loaded, eventPhase: 2, …}

**Comment by ricschuster** [comment]
'Open sidebar to evaluate solutions' is greyed out. Works to look at (all) solutions after optimization is run, but once I click on "Open sidebar for generating new solutions" I can't get back and need to run a new scenario to get there again.

**Comment by ricschuster** [comment]
Everything else seems to work well.

**Comment by jeffreyhanson** [comment]
Awesome - thanks so much for catching all these issues. I'll take a look and see what I can do.

**Comment by jeffreyhanson** [comment]
It seems like the screenshot issue be associated with the underlying Javascript library (https://github.com/rowanwins/leaflet-easyPrint/), because there are several issues that mention a similar error (see https://github.com/rowanwins/leaflet-easyPrint/search?q=CORS&type=issues). So I don't think this is something I can easily solve. Given that, would you prefer (1) keep this functionality and just have the screenshot stuff not work on MS Edge, or (2) remove the screenshot stuff entirely so that the app gives a consistent experience on all browsers?

**Comment by jeffreyhanson** [comment]
> It seems like the screenshot issue be associated with the underlying Javascript library (https://github.com/rowanwins/leaflet-easyPrint/), because there are several issues that mention a similar error (see https://github.com/rowanwins/leaflet-easyPrint/search?q=CORS&type=issues). So I don't think this is something I can easily solve. Given that, would you prefer (1) keep this functionality and just have the screenshot stuff not work on MS Edge, or (2) remove the screenshot stuff entirely so that the app gives a consistent experience on all browsers?

I was able to borrow a computer with Edge installed and it seems like it's only a problem for the Stamen basemap - so perhaps one fix is to replace the Stamen basemap with a different one? What do you think? If that sounds like a good idea, can you take a look through the leaflet basemap providers (see https://github.com/rstudio/leaflet.providers) and tell me which one should be used instead of Stamen?

**Comment by ricschuster** [comment]
> I was able to borrow a computer with Edge installed and it seems like it's only a problem for the Stamen basemap - so perhaps one fix is to replace the Stamen basemap with a different one? What do you think? If that sounds like a good idea, can you take a look through the leaflet basemap providers (see https://github.com/rstudio/leaflet.providers) and tell me which one should be used instead of Stamen?

That sounds promising.
I've used `CartoDB.Positron` before. Maybe that one works?

**Comment by jeffreyhanson** [comment]
Ok, I'll try that and see if it works.

**Comment by jeffreyhanson** [comment]
I've added the CartoDB Dark Matter map (because it's monochromatic, and so a better replacement for the Stamen toner map) and  checked that the screenshot functionality now works on MS Edge. I also updated the sidebars yesterday so that they now work on Firefox, and this update also fixed the sidebar issues on MS Edge too. So, I think this has addressed all the MS Edge issues - so I'll close this issue now. Please freel free to re-open this issue if you find any more bugs/errors/issues with running the app on MS Edge.
