### ISSUE TITLE
weights don't seem to affect solutions as much as expected

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#133]
This is probably due to some bug when transforming the weight values.

**Comment by jeffreyhanson** [comment]
This bug was caused by two underlying issues. Specifically, the continuous legends were displaying values incorrectly (they were reversed such that high values were depicted with the color for low values, and vice versa), and the code used to calculate cost values based on the weight status values was incorrect.

**Comment by ricschuster** [comment]
I thought there was something strange going on with the weights. Great to hear that you have identified the source.

**Comment by jeffreyhanson** [comment]
Yeah, sorry abou that, it should be working now. I fixed with commit 2c09103f06c3ffbd5e2c46e08e6298121641444b fixed (but accidently tagged it with the wrong issue number). Let me know if something strange is still going on though, and I can look into it further?
