### ISSUE TITLE
Turn off solutions on main map

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#135]
Joe had this comment about the app:

> How to turn off solutions on main map – multiple runs stack but I can’t find a way to turn them on and off on the map.

The solutions should be able to be toggled on/off by clicking the eye icon/button (similar to the other layers), so I think this functionality is already present in the app - maybe this just needs to be emphasized in the manual?

**Comment by jeffreyhanson** [comment]
@josephrbennett, have I got this right? Does clicking the eye icons for the solutions provide the desired functionality? Or did you mean something esle? Sorry if I'm missing something.

**Comment by josephrbennett** [comment]
THanks - will retry. Server crashed tonight.

**Comment by jeffreyhanson** [comment]
Ah ok - no worries. I'm manually pdating the apps on the server, so give me a moment to get them running again.

**Comment by jeffreyhanson** [comment]
Ok, I've got the updated apps running on the server now.

**Comment by josephrbennett** [comment]
OK, great! Thanks a lot. New icon looks great. I was wondering if say one does several runs, if one can turn certain ones (rather than all) on and off at will - analogous to the eye icon but with more flexibility?

![map (1)](https://user-images.githubusercontent.com/33939350/129644428-b67a1540-bf94-468f-ab5e-74edaccbee42.png)

**Comment by josephrbennett** [comment]
We can see in attached map that there's overlap between one run (blue) and another (red) - overlap is purple. Would be great to be able to turn one or another off?

**Comment by jeffreyhanson** [comment]
Yeah, you can use the eye buttons in the sidebar to toggle individual layers on/off on the map. So, you could use this to turn one solution on and another solution off. Does that provide the functionality you're looking for? Sorry if I'm missing something.

![Screenshot_20210817_122925](https://user-images.githubusercontent.com/3610005/129645514-60e508e4-cb89-470e-af30-089ecff4481c.png)

**Comment by josephrbennett** [comment]
Yes, I'm sorry - that's perfect! Sorry I missed it.

**Comment by jeffreyhanson** [comment]
Ah -no worries - I'll close this issue now since we've resolved it.
