### ISSUE TITLE
Solution name text input

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#138]
Joe had this suggestion for the app:

> For new solution, allow longer names for those who like naming things according to run parameters?

The current character limit is the maximum we can do unless we (1) increase the width of the sidebars (not easy to do and will likely mean lots of work re-aligning sidebar components), (2) decrease the font size, (3) add a second lager text box so that users can input more verbose information (e.g. like a description box), or (4) are happy with text side-scrolling (e.g. [go to here](see https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_test)) and start typing letters into the text box, if the number of characters exceeds the box width, then it horizontal side-scrolls so you can keep typing stuff and see what's inside the box. @ricschuster and @josephrbennett, how do you think we should proceed?

**Comment by josephrbennett** [comment]
I don't see an issue with side-scrolling, but this is such a small issue that I'm happy to go with whatever is easiest and you like best. Thanks!

**Comment by jeffreyhanson** [comment]
Ok sounds good. @ricschuster, what do you think? IIRC we had some discussion about this and you had concerns that the horizontal side-scrolling might confuse users (e.g. they might mistakenly think that the text was being deleted)?

**Comment by ricschuster** [comment]
I might remember this wrong, but I thought we mostly talked about (1). I think (4) would be okay for the app, but wasn't there something in either the results tab/tables or with the download table that could be an issue? Might just be my imagination, but I thought we had concerns about that.

**Comment by jeffreyhanson** [comment]
Ah, yeah, that might have been it. I'll play around with it and see what I can do.

**Comment by jeffreyhanson** [comment]
I've just pushed an update that increases the maximum character length from 21 to 50. If more than ~20 characters are used for a solution name, then only the first ~20 characters will be visible given the length of the picker input (i.e. solution name select button/drop-down menu combo). However, the full name can be viewed by clicking on the picker input, because the width of the drop-down menu will automatically expand as needed so we can the full names. This update affects both picker inputs in the solution results sidebar and the solution results modal (i.e. what you see when clicking the button to view the tabular results).
