### ISSUE TITLE
themes vs includes - shutting off both causes crash?

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#142]
I've left it running for a while so may resolve, but it looks like shutting off all themes and includes causes a crash. Obviously not a real scenario, but I'm trying to break it... 

Maybe this is a coincidence, but things seem otherwise stable and I've tried it 2X. Perhaps there needs to be a stop and a warning instead?

**Comment by jeffreyhanson** [comment]
Thanks so much for catching this. It's not really valid to generate a solution without a single theme toggled on, so I'll have it throw a error popup if users try generating a solution without a theme --- meaning that they shouldn't encounter this crashing issue.
