### ISSUE TITLE
Pilot prep including features per theme

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#144]
@jeffreyhanson, how would I need to modify this script:
inst/scripts/format-ontario-pilot-data.R
to allow for more than one feature per theme?

**Comment by jeffreyhanson** [comment]
Yeah, when creating a theme using the `new_theme()` function, you would pass in a list of `Feature` multiple objects instead of a single `Feature` object (see [here](https://github.com/NCC-CNC/wheretowork/blob/master/tests/testthat/test_new_theme.R#L187-L214) for example).

**Comment by ricschuster** [comment]
Cool, thanks!
