### ISSUE TITLE
Solution table slight syntax issue

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#146]
The solution table weights have some strange font, e.g. "<div>Aggregate </div><div>Threats</div>"

**Comment by josephrbennett** [comment]
sorry, didn't come through correctly: <div>Aggregate </div><div>Threats</div>

**Comment by josephrbennett** [comment]
Ugh...  not coming through github comment pane... if you have a look at a run you'll see what I mean.

**Comment by jeffreyhanson** [comment]
Thanks for catching that! Yeah, I know what you mean - I'll fix that now.
