### ISSUE TITLE
Possible non-issue: when weights set to 100, solution can be less than current

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#148]
sorry if I'm missing something glaringly obvious... When weighting roads at 100 and locking in protected areas (only - not buffers or policy areas), it appears that the solution has less road than current. See file. 
[hgghg_weight_results.xlsx](https://github.com/NCC-CNC/wheretowork/files/7010577/hgghg_weight_results.xlsx)

**Comment by jeffreyhanson** [comment]
Yeah, so weights are things we want to avoid in the solutions. Specifically -- for the min set formulation (i.e. no budget) -- the weight data are used to specify "cost" values for the optimization run (and the relative importance of different weights is based on their relative factors [i.e. slidebar value]). So, we would expect increasing the factor for a weight to result in solutions that have lower coverage of the weight. Does that explain the behavior you're seeing?

**Comment by josephrbennett** [comment]
Right on - thanks! Maybe we can discuss when we meet, just so I'm clear?

**Comment by jeffreyhanson** [comment]
Sorry - I completely forgot to respond to your message. Yeah, we can chat about this during our next meeting.

**Comment by jeffreyhanson** [comment]
I think we've resolved this issue now that the weights are treated differently inside the app, so I'll close this issue now. Please feel feel free to reopen this if you encounter a similar issue.
