### ISSUE TITLE
Baselayers

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#151]
This is totally a personal preference, but I find the Monochrome baselayer way too dark and would rather include something light like `CartoDB.Positron`. 

Might be worth asking a couple people about this to determine what most people like and go with that?

**Comment by jeffreyhanson** [comment]
No worries - I'm happy to add `CartoDB.Positron`. I'll do that now.

**Comment by jeffreyhanson** [comment]
This issue was fixed by 43e23253ce65c24057c76b9968e79630ae206913
