### ISSUE TITLE
BC pilot error

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#158]
Here the repo with all the files for this issue: https://github.com/ricschuster/Tool1_pilot_BC
`prep_Tool1_update.R` has the code for prepping the data for the app.

When I upload the project files `/out/bc_pilot/*` the app loads them alright. I can see the layers and everything, but when I try to run the optimization I get an error:

![image](https://user-images.githubusercontent.com/3445092/131162734-22ed44fe-aa4d-4b2f-b235-9b800fa7f0a2.png)

I've tried many different ways (min_set, min_shortfall, changing targets, playing with weights), but I always get the error.

I did try to run prioritizr on the problem (Lins 225+ in `prep_Tool1_update.R`) and that works just fine.

@jeffreyhanson could you have a look and see if you can figure this out?

**Comment by jeffreyhanson** [comment]
I've just pushed an update so that the prioritization functions will automatically remove planning units with no weights/themes/includes (i.e. planning units where all such data are zero). This seems to fix the issue on my system - let me know if you still run into issues?

**Comment by ricschuster** [comment]
Thanks very much Jeff! Its working for me too.

Why do you think this is an issue in the app, but when I run the prioritzr code that's in the prep_Tool1_update.R script ((Lines 225+) it works okay?

**Comment by jeffreyhanson** [comment]
Oh - I dunno. The app does a bunch of re-scaling stuff to avoid potential numberical issues (see https://github.com/NCC-CNC/wheretowork/blob/master/R/fct_min_set_result.R#L248-L271), maybe that combined with the sparsity was causing issues?

**Comment by ricschuster** [comment]
Thanks Jeff! Great to see that its working.
