### ISSUE TITLE
Project import error message

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#159]
When trying to upload a project dataset that was compiled with the `write_project` function I sometimes get an error message like this:

![image](https://user-images.githubusercontent.com/3445092/132053479-aca78890-4e8b-43fb-a4aa-e2b301429676.png)

Most of the time I'm able to figure it out, but I was wondering if you can think of a way to make those error messages a bit more informative?

**Comment by jeffreyhanson** [comment]
Have you tried uploading this project dataset to a version of the app that is runing locally on computer (e.g. launched via the system command `make debug`)? IIRC,  it should print the R error message to console when you do this?

**Comment by jeffreyhanson** [comment]
We could add something like a download error log option to the app that contains a traceback for the error. Would that provide the functionality you're looking for? If so, should this option be provided in both the beginner and advanced modes, or just the advanced more?

**Comment by jeffreyhanson** [comment]
@ricschuster, could you send me a copy of the project dataset that's not working? This would help me ensure that the downloaded error log contains useful information.

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson !
Its the current project dataset here: https://github.com/ricschuster/Tool1_pilot_BC
Located in out/bc_pilot/
The `sar_theme` is the issue.

**Comment by ricschuster** [comment]
> 
> 
> We could add something like a download error log option to the app that contains a traceback for the error. Would that provide the functionality you're looking for? If so, should this option be provided in both the beginner and advanced modes, or just the advanced more?

Depending on how you envision serving this information up to the user, it would be useful to have it in both modes I think. This way beginners can copy/paste the log and ask for help.

**Comment by jeffreyhanson** [comment]
> Thanks @jeffreyhanson !
> Its the current project dataset here: https://github.com/ricschuster/Tool1_pilot_BC
> Located in out/bc_pilot/
> The `sar_theme` is the issue.

Ah ok - thanks!

> Depending on how you envision serving this information up to the user, it would be useful to have it in both modes I think. This way beginners can copy/paste the log and ask for help.

Ok sounds good!

**Comment by jeffreyhanson** [comment]
In addition to providing the option to download the error log, I was thinking it might be helpful to provide instructions to tell the user to email the error log to a person to resolve this issue. At the moment, this would just be you because you're the only person creating the projects. However, in the future, other people will be creating projects too. As such, should the project configuration file contain a field with the email address of the person who created the project, so the app can tell the user to email this person the error log?

**Comment by jeffreyhanson** [comment]
Or should all error logs be reported to you?

**Comment by ricschuster** [comment]
> 
> 
> Or should all error logs be reported to you?

Lets do that for now. Adding an email field to the project file would be good though, so we can use it later if we want to.

**Comment by jeffreyhanson** [comment]
Ok - can do. I can also update the app to default to your name and email address if the project configuration YAML file is missing these fields.

**Comment by ricschuster** [comment]
> 
> 
> Ok - can do. I can also update the app to default to your name and email address if the project configuration YAML file is missing these fields.

Thanks Jeff!
I like the 'default to' idea.

**Comment by jeffreyhanson** [comment]
Ok, so the app will now show the following popup when/if projects (both built-in and manual upload)  fail to import:

![Screenshot_20210908_114212](https://user-images.githubusercontent.com/3610005/132428170-ee6793d4-f6d0-4e8b-9059-c6788f8b1d88.png)

If you download the error link, you get a zip file with (1) the project configuration YAML file (I figure this would be handy to include) and (2) an `error-log.txt` file (in markdown format) containing details on the error(s). For example, here is the contents of the error log txt file  when trying to import the BC example data:

```
# wheretowork error log

## Summary

Failed to import the following Themes: "SAR"

## Details

### SAR

Error : categorical data has 1 unique values and so the argument to "colors" must contain this many elements.

```

I've also updated the error handling in `read_project` to check all themes/weights/includes for errors and then return all layers/data with issues in the log.

What do you think? Are there any more details worth including in the log? Note that this log is designed to be specifically for handling the import of project data. So, I don't know if it's worth including additional stuff like `sessionInfo()` or date time stamps that would be relevant for tracking down bugs/crashes in the application (such information can be accessed from the shinyproxy log files).

**Comment by ricschuster** [comment]
This is great! Thanks very much Jeff!

**Comment by jeffreyhanson** [comment]
Ok - excellent  - I'll push update to GitHub, close the issue, and update the version of the app on the server.

**Comment by jeffreyhanson** [comment]
Ok - done.
