### ISSUE TITLE
Unicode characters should be allowed in the "Units" field in Yaml config file

### ISSUE THREAD

**Issue by JCLaurence** [NCC-CNC/wheretowork#167]
Hi Jeff!  In the Table of contents, the "units" value tends to wrap to the next line when it gets a bit too long.  This max length isn't very long, and wrapped text makes the legend a bit tricky to read.  There seems to be a lot of usable whitespace in the table of contents to the right of the labels.  Can you see if the label length could be extended a bit?   This is pretty minor.  My screen cap doesn't show wrapped labels, I just realized.

![image](https://user-images.githubusercontent.com/65399677/133786619-073577cc-4762-4f86-a2a2-e3b2c27b27c7.png)

**Comment by JCLaurence** [comment]
I also just realized that my Issue Title has absolutely nothing to do with the issue content!  Ignore the title, just read the sentences I wrote :)    I also realize that the "unit" length is limited in the Theme / Feature listing on the right side of the app, which means there may not really be any point in extending unit length in the legend...

**Comment by jeffreyhanson** [comment]
Hi @JCLaurence! Thanks for posting this issue - I'll look into it and you know how I go. 

PS. for future reference, you can change the name of the issue by clicking the "Edit" button next to "New Issue" at the top of the page (next to the issue title).

**Comment by jeffreyhanson** [comment]
@JC - I'm having trouble reproducing this issue - can you please send me the example project data you used to produce this error?

**Comment by JCLaurence** [comment]
Hi Jeff!  Disregard the issue title!  I thought I had mentioned this in one of my comments on this issue...  I posted the issue, solved my units display problem, then realized I hadn't changed the name of the post!
JC

________________________________

**Comment by jeffreyhanson** [comment]
Ah ok - so is the issue resolved then? If so, I'll close the issue?

**Comment by JCLaurence** [comment]
Yes resolved

Sent from my iPhone

On Sep 26, 2021, at 3:37 PM, Jeff Hanson ***@***.***> wrote:

﻿
ATTENTION:External Email|Courriel Externe
________________________________

Ah ok - so is the issue resolved then? If so, I'll close the issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCC-CNC%2Fwheretowork%2Fissues%2F167%23issuecomment-927358874&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Cb1a801d84d4f401bfa8a08d98125204b%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637682818722381058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tbH7l8PTxxgW1eQaw9iPRuuF1IAsricsKs7tGOBjVAw%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPS6W7OUVXR5VZHU4V66LR3UD6AB3ANCNFSM5EHAZYJA&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Cb1a801d84d4f401bfa8a08d98125204b%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637682818722391013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gueSTyqfE%2FOJqbCuhrbCiXt9gEn9IiG01R2ZoCkW4Hk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Cb1a801d84d4f401bfa8a08d98125204b%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637682818722391013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VE%2F4QFiSSeO6ErdJ5jkRXVmdI3FI2HQvlfSBUcDQgaM%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Cb1a801d84d4f401bfa8a08d98125204b%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637682818722400967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B6g6wnWk%2B83xLHhwPRITGwBOaxBBP3Dx1eXUxE7KnRc%3D&reserved=0>.

**Comment by jeffreyhanson** [comment]
Ok - thanks for clarifying that.
