### ISSUE TITLE
Ontario prioritization fails

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#173]
Hi Jeff,

I've updated the Ontario data and everything loads alright, but I do get the following error if I try to run a scenario:

`Error in cpp_cbc_solve(obj = obj, isMaximization = max, rowIndices = mat@i,  : 
  c++ exception (unknown reason)`

Do you have an idea what could be causing this?

I've made changes to `format-ontario-pilot-data.R`. The biggest change was moving the TNC layers from themes to weights.

**Comment by jeffreyhanson** [comment]
Ok, I'll take a look and see what I can do. Not sure, I noticed this sometimes happens when there numbers that are really small (e.g. 1e-10).

**Comment by ricschuster** [comment]
Thanks Jeff!
Were you able to have a look at this? If not, I can.

**Comment by jeffreyhanson** [comment]
Sorry I forgot about this, I'll take a look at it this morning.

**Comment by jeffreyhanson** [comment]
I think I've worked it out - it's due to data sparsity issues where planning units in the last columns of the rij matrix don't contain any data. To address this, I'll add in a fake feature with randomly generated values to ensure that every column in the rij matrix has at least some data.

**Comment by jeffreyhanson** [comment]
Also, I'm not sure how useful it is to have the "policy areas" and "A2A areas" as the weights. This is because (1) setting a positive weight will only increase their coverage by the solution, whereas a "distance from policy/A2A area" would be more meaningful a as a weight, and (2) the beginner mode assumes that all weights are "bad" for "conservation" and assigned a negative weight of -99 -- which I imagine does not apply in such cases?

**Comment by jeffreyhanson** [comment]
Just updated the version on the server, let me know if you still run into any issues?

**Comment by ricschuster** [comment]
> 
> 
> I think I've worked it out - it's due to data sparsity issues where planning units in the last columns of the rij matrix don't contain any data. To address this, I'll add in a fake feature with randomly generated values to ensure that every column in the rij matrix has at least some data.

Thanks very much! Its working now.

**Comment by ricschuster** [comment]
> 
> 
> Also, I'm not sure how useful it is to have the "policy areas" and "A2A areas" as the weights. This is because (1) setting a positive weight will only increase their coverage by the solution, whereas a "distance from policy/A2A area" might be more meaningful as a continuous option for accounting for these places, and (2) the beginner mode assumes that all weights are "bad" for "conservation" and assigned a negative weight of -99 -- which I imagine is not correct for such cases?

Thanks for letting me know. This is what the region asked for so they can play around with things. When I talk to them next, I will bring this up.
