### ISSUE TITLE
download link for user manual

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#188]
The help popup should contain a download link for the user manual for the tool. This is important so that users can easily access the user manual. Note that the user manual is still being written, so we'll need to wait until it's finalized before we can address this issue.

**Comment by jeffreyhanson** [comment]
Chatting today with @ricschuster and we talked about embedding the maunal in the tool source code and providing a link to the internal version.

**Comment by jeffreyhanson** [comment]
@ricschuster, I just want to confirm if I can embed the current version of the manual into the tool - or does it need further editing before we should do this? E.g., adding the manual to the tool will make the manual public, which might not be desireable if it's still incomplete (e.g. missing attributions, etc)?

**Comment by ricschuster** [comment]
@jeffreyhanson could you share the version you are using so I can have a look? I think its pretty much ready to put online.

**Comment by jeffreyhanson** [comment]
Ok - based on the meeting yesterday, it sounds like the manual is still being worked on. So, let's hold off on adding it to the repo until it's pretty much finished?

**Comment by ricschuster** [comment]
I think that was for the "What To Do" tool, but happy to wait for a bit for sure.
