### ISSUE TITLE
multi-theme-result hover label with long feature names not properly sized to the viewport 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#210]
Features that have long names (i.e. R1km_T_SPECIES_SAR_SC_Invertebrates_anthropods_Yellow_namded_Bumble_Bee) run off the screen

![image](https://user-images.githubusercontent.com/29556279/171033072-e464b310-337c-4478-899d-a9dae2277164.png)

Adding a `word-break: break-all;` should fix this:

![image](https://user-images.githubusercontent.com/29556279/171033485-a299519c-3fd8-4029-96c7-9bca0ad36fd8.png)

**Comment by jeffreyhanson** [comment]
Brilliant - thank you for reporting this and finding the fix!

**Comment by DanWismer** [comment]
I don't see this happening anymore .... will close for now
