### ISSUE TITLE
'Launching Where To Work' hangs

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#215]
`Where to Work` currently only launches using the `admin` account. If I used public or other users the app hangs and generates the following error message:

![image](https://user-images.githubusercontent.com/3445092/173130436-ddaf4b16-40ae-4fca-9e8c-24c3de6560cf.png)

**Comment by ricschuster** [comment]
I did two things before this happened:

1) Update server packages and did a reboot

2) added or changes a `user_groups` line to the project yaml files
```user_groups: staff-advanced```

**Comment by ricschuster** [comment]
I am guessing this is related to 2, but didn't want to change things back yet in case you want to use the current state to troubleshoot what's happening.

**Comment by DanWismer** [comment]
I think what I can do is navigate to ~/Github/web-apps folder and run the docker logs command to see if there is any other debugging info

**Comment by DanWismer** [comment]
There error looks to be in the project_configs list. One of the items is not a logical but a character:

![image](https://user-images.githubusercontent.com/29556279/173140877-4baea37a-8fc6-4f49-99b3-11a330c8731d.png)

**Comment by DanWismer** [comment]
I think `user_groups` can be of only 2 options:
1. public
2. admin

Where `mode` is  where you set:
1. beginner
2. advanced
3. project

**Comment by ricschuster** [comment]
Interesting.
In the code snippet above I see "private". Where does this come into play?
What would I need to set in the yaml file to make sure a project is not visible to public?

**Comment by DanWismer** [comment]
Ah yes, I caught that as well. It looks like public and admin are the two options you can set manually. Where the private user_group is set programmatically. Will run a test and see what's happening

**Comment by DanWismer** [comment]
If you set the user_group to admin, my understanding is that the dataset should only be available when logged-in as admin

**Comment by ricschuster** [comment]
and if I don't set it at all it should only be available to users other than public, is that correct?

**Comment by DanWismer** [comment]
I think I confused myself a bit. My bet is you want the dataset to also show in the staff-advanced log in as well...

**Comment by ricschuster** [comment]
Yes. I essentially want a project to show when a person logs in with any username other than 'public'.

**Comment by jeffreyhanson** [comment]
Hmm, looks like there might be a bug. This is because line 61 in `fct_find_project.R` should return a logical (TRUE/FALSE), but instead returns a character value. Could you try changing `return(NA_character_)` to `return(TRUE)`?

**Comment by jeffreyhanson** [comment]
The `user_groups` field in the project YAML file should be a value (or an array containing values) that correspond to the login groups on the web-apps repo. These currently include: `public`, `private`, `staff-beginner`, `staff-advanced`, `admin`.

**Comment by jeffreyhanson** [comment]
So, if you want a project to be available for all groups except public, I would try setting:

```
user_groups: [ "private", "staff-beginner", "staff-advanced", "admin" ]
```

**Comment by jeffreyhanson** [comment]
That said, if the `user_groups` variable is specified correctly in the project YAML file, I don't see why it's throwing this specific error.

How urgent is this? It's Saturday here, but can try to debug if this is urgent. If not, can we tackle this during our meeting on Tuesday (my time)/Monday (Dan's time)?

**Comment by ricschuster** [comment]
Thanks Jeff!

Not urgent. Next week is totally fine.
