### ISSUE TITLE
Leaflet: Size limitations of raster images

### ISSUE THREAD

**Issue by XavierCLL** [NCC-CNC/wheretowork#217]
Hello all,

I am working on a project called CAP-BC more related to conservation planning focusing on climate change in BC, Richard is partially part of this project too. I was working with PrioritizR with Shiny but I realized that Where to Work has the features that the project needs and I am adjusting this app to the project, so I'll here asking things and maybe pushing some PR.

The first issue (and very important for me, and Richard told me something about it) is the size limitations of raster images. I can add and process them perfectly but when I try to load the project in the webtool, the terminal shows an error:

> Warning: Error in leaflet::addRasterImage: Raster image too large; 1356573 bytes is greater than maximum 1048576 bytes
> [No stack trace available]

I have tried changing the values to 0-100 and converting the data type to Byte, the final size of the tif (LZM compression) is around 600 Kb, it is not big. There is no way to reduce the size of the image without losing information (like converting the data 0-10, or binary 0-1) but I don't want to lose data of the layers. Any idea How to solve it? or avoid it? or any trick?.

Thanks so much,
Xavier

**Comment by jeffreyhanson** [comment]
No worries! Great to hear it worked - I'll close this issue now, but please feel free to re-open if you have any further questions.
