### ISSUE TITLE
Legend Labels  

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#218]
- It would be nice to have control on individual category labels on the legend to make them more descriptive to the user. Currently, when you specify `units`, it labels all categories the same. 
- Ability to superscript legend labels 

![image](https://user-images.githubusercontent.com/29556279/178804743-6e146f4d-49a3-4d66-a171-6b5b0c0b410c.png)

**Comment by DanWismer** [comment]
test driven approach:
- modify simulate weights and themes function so that they can build with a manual legend if flagged to do so
- generate new sim_raster_data4 to test on

**Comment by DanWismer** [comment]
@jeffreyhanson

If themes and/or weights have a manual legend; an error occurs when reading in the project data (`fct_read_project`). When the `read_project` function is called,  the `new_variable_from_auto` `Variable` method is used on themes and weights. I am thinking we should change this to use the `new_variable` function instead, as we don't need to recalculate metadata. We should see a little performance boost as well? Using the `new_variable`, we can then add some logic to asses is a continuous, categorical or manual legend should be built. 

Am I on the right track?

**Comment by jeffreyhanson** [comment]
Hmm, I think the `new_variable_from_auto` function is used so that the code can automatically run some calculations (such as calculating the "total" amount in the GIS layer). If you switch to `new_variable`, then you'll have to do these calculations yourself - which could be a bit annoying since you'll need to do this in a data-format-agnostic way (i.e., in a way that works for both vector and raster data). To minimize the amount of work needed, I would suggest updating the `new_variable_from_auto` function to work with manual legends. How does that sound?

**Comment by DanWismer** [comment]
Bingo! 

Thanks for that suggestion Jeff. I was able to get it to work by adding an additional parameter, `labels = "missing"` to the `new_variable_from_auto` and pass that `labels` metadata to the `new_variable_from_metadata` to create a `new_manual_legend` if `metadata$type == "manual"` 

![image](https://user-images.githubusercontent.com/29556279/180258842-4e1acc5b-42ac-4ed6-8cbd-8f57de454051.png)

Now the trick is to remove the units that are appended to the end of each label (just for manual legends within the map manager). It would be nice for manual legends to not have that. I think it makes sense to have in the map manager, say for species labels, `value 0: absence and value 1: presence (km2)`. But sill keep the units (km2) defined for the solution settings / results.

**Comment by DanWismer** [comment]
I think I found where I can edit the appended untis text. It is within the mapManager html widget. I found the `categoricalLegend.js` script and see that on line 41, the `.innerText` is defined. Odd thing is that I have made an edit to that line, but no behavior changes when I run in dev mode.

![image](https://user-images.githubusercontent.com/29556279/180304025-31a8c028-d21c-413e-af40-fe339b0895d0.png)

Is there something I need to run for changes in the htmlwidgets code to be seen? I figured `devtools::load_all()` would do the trick?

**Comment by DanWismer** [comment]
oh, disregard the last comment. I refreshed my RStudio session and it is working now...

![image](https://user-images.githubusercontent.com/29556279/180307994-eeded4f4-ae85-42a9-a1ea-1a09bc0a4d3a.png)

**Comment by jeffreyhanson** [comment]
Awesome - yeah - great to see you got it working. Sorry, I don't know why you needed to refresh Rstudio - I would have thought using just `devtools::load_all()` would be sufficient.

**Comment by DanWismer** [comment]
- added new `ManualLegend` class to htmlwidgets. This now handles manual legends in the `mapManager` and does not append the units to the labels.
- `CatagoricalLegend` class is the same (appends units to the values)
