### ISSUE TITLE
rcbc installation source

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#237]
The DESCRIPTION file specifies that the rcbc package should be obtained from the remote `jeffreyhanson/rcbc`. It should instead refer to the official source which is `dirkschumacher/rcbc`. When you get a chance @DanWismer, could you update it?

**Comment by DanWismer** [comment]
I have changed the `Remotes:` to `dirkschumacher/rcbc` in the `DESCRIPTION` file. I beleive the next step is to do a `renv::snapshot(type = "explicit")`

This gives me the following message:
![image](https://user-images.githubusercontent.com/29556279/192367341-209ab2e6-55bf-49e2-9956-d1e4a7446539.png)
 
I think I am good to say yes? need a refresh myself on the renv stuff...

**Comment by jeffreyhanson** [comment]
Yeah thats fine - it's just asking to confirm if you want to update the version of rcbc in renv

**Comment by DanWismer** [comment]
@jeffreyhanson I think something is up with installing rcbc with `wheretowork`

![image](https://user-images.githubusercontent.com/29556279/192875537-ea4d1428-c4b5-43ac-9686-47ad8a427905.png)

**Comment by jeffreyhanson** [comment]
Ah that's odd - can you install it normally on your computer (i.e., outside of renv)?

**Comment by DanWismer** [comment]
We get this:
![image](https://user-images.githubusercontent.com/29556279/192877779-aa2fa06f-1f01-4956-af5e-6f02ef433840.png)

**Comment by jeffreyhanson** [comment]
Hmm, do they have rtools installed on their computer?

**Comment by jeffreyhanson** [comment]
Also, anything before the `ERROR: .....`?

**Comment by jeffreyhanson** [comment]
Also, anything before the `ERROR: .....`?

**Comment by DanWismer** [comment]
This is the full message:
![image](https://user-images.githubusercontent.com/29556279/192878396-3d9a13b3-9c3e-40be-83bf-49704aad0fc9.png)

**Comment by jeffreyhanson** [comment]
what if they try R 4.1.2?

**Comment by jeffreyhanson** [comment]
I dunno sorry, I would have expected this to work. @ricschuster, can you try installing rcbc on your computer? Would be good to work out if this is a rcbc or personal computer issue.

**Comment by jeffreyhanson** [comment]
is this 32 bit or 64 bit R? I'd recommend trying with 64 bit if possible.

**Comment by jeffreyhanson** [comment]
Looks like Windows installation for rcbc might not work on R version 4.2+ (see "Linking to pre-built static libraries" in https://cran.r-project.org/bin/windows/base/howto-R-4.2.html)

**Comment by jeffreyhanson** [comment]
Quick fix might be to downgrade R to 4.1.3, uninstall rtools42, install rtools40, and then try rcbc. Better solution would be to update rcbc - but dunno how to do this.

**Comment by ricschuster** [comment]
> Looks like Windows installation for rcbc might not work on R version 4.2+ (see "Linking to pre-built static libraries" in https://cran.r-project.org/bin/windows/base/howto-R-4.2.html)

Yes, I think that's it or I at least vaguely remember running into that issue.

**Comment by DanWismer** [comment]
ok cool we will give the downgrade a try and see what happens. Thanks for all this insight

**Comment by jeffreyhanson** [comment]
If you still have 4.2.1 handy, could you try installing this `remotes::install_github("jeffreyhanson/rcbc@ucrt")`? Just had an idea for a potential quick fix

**Comment by DanWismer** [comment]
> Quick fix might be to downgrade R to 4.1.3, uninstall rtools42, install rtools40, and then try rcbc. Better solution would be to update rcbc - but dunno how to do this.

Awesome, we got it to work. I am wondering how we should communicate this with new users?

**Comment by jeffreyhanson** [comment]
Hmm, we ideally want to get rcbc working on 4.2+ - so that prioritizr users can use rcbc too. For the moment, maybe consider updating the wheretowork README to mention Windows users need to use R 4.1.3 and it doesn't work on 4.2+?

**Comment by jeffreyhanson** [comment]
If the uct branch doesn't work, @DanWismer, could you try following the instructions under "Using findLinkingOrder with Rtools42 (tiff package example)" to find the correct linker flags (but substituting cbc as needed)?

**Comment by jeffreyhanson** [comment]
Just to keep you in the loop, I've been playing around with this and I think Ive found a fix. To address this, I've submitted a PR to RWinLib to provide updates CBC files for R version 4.2+ (https://github.com/rwinlib/cbc/pull/3) and a PR to rcbc to use these udpates files during installation (https://github.com/dirkschumacher/rcbc/pull/66). Once/if both of those are merged, rcbc should work on R version 4.2+ so we can upate wheretowork to use the latest rcbc version and, in turn, work on R version 4.2+.

**Comment by DanWismer** [comment]
Thanks Jeff! That all sounds promising. Hopefully they can will merge in those PR's. I will stay tuned.

**Comment by jeffreyhanson** [comment]
Just to let you know, the PRs have now been merged, so it might be worth trying to udpate the rcbc version renv?

**Comment by DanWismer** [comment]
awesome! lets do it

**Comment by DanWismer** [comment]
PR #276
