### ISSUE TITLE
Error with the wheretowork docker image

### ISSUE THREAD

**Issue by XavierCLL** [NCC-CNC/wheretowork#244]
Hi,

Recently I tried to run my own local wheretowork clone but suddenly it shows me the following error:

```bash
 => exporting to image                                                                                                  10.7s
 => => exporting layers                                                                                                 10.7s
 => => writing image sha256:0cc7bd6d9947885d088cb07f99cb8b3fd48e3332e5a8e348f2e47796366c653f                             0.0s
 => => naming to docker.io/naturecons/wheretowork                                                                        0.0s
[+] Running 1/1
 ⠿ Container cap-bc-webtool-app-1  Created                                                                               0.1s
Attaching to cap-bc-webtool-app-1
cap-bc-webtool-app-1  | Error in loadNamespace(x) : there is no package called ‘wheretowork’
cap-bc-webtool-app-1  | Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
cap-bc-webtool-app-1  | Execution halted
cap-bc-webtool-app-1 exited with code 1
```

I have tried cleaning all the docker cache and pulling and building again the docker-compose and nothing, it continues with that issue, any ideas?

Thank you guys!

Xavier

**Comment by DanWismer** [comment]
Hi Xavier,

I am wondering if it has to do with container `cap-bc-webtool-app-1`. I notice that if I don't stop and remove a container, and then do docker-compose, it causes me problems and advances the name of the container (ex. `cap-bc-webtool-app-1`, `cap-bc-webtool-app-2`, `cap-bc-webtool-app-3`. etc.)

Some other useful docker commands is `docker ps -a` and then I take the `ID` and explicitly do a `docker rm -f bc9ed815be02` to force remove the container.

With images, sometimes I get these `<none>` REPOSITORY: 
![image](https://user-images.githubusercontent.com/29556279/191287226-96a2af88-27f6-49c6-9bc6-429493b3dd78.png)
I am not sure why that happens, but I force remove those as well.

Not sure if any of this will help your problem

**Comment by XavierCLL** [comment]
Hi @DanWismer 

Thanks for your response, and yes I did it, I cleaned all docker images, cache and overlay2, I even deleted everything docker configurations and volumes (deleting the `/var/lib/docker` in Linux) to build from scratch and nothing, same error.

Either there is something happening with my docker on my computer (but I dough it, other docker images work) or you don't have that issue because you are using the docker cache for that 'wheretowork' image... I need to test it more when I have more time.

Anyway many thanks,
Xavier

**Comment by XavierCLL** [comment]
I found the issue!

I'm gonna describe this as a reference to this issue if someone has a similar problem because the error is not descriptive. I used a symbolic directory to test some data into the project directory, but in general docker container can't open symlinked file in volume mount during startup, and that was the issue.

**Comment by DanWismer** [comment]
Nice work finding the issue! Ok that is good to know. I also had to hard code full file paths to attach data on my C: drive as a volume. When I use relative paths, the data never showed in the local Docker container.
