### ISSUE TITLE
Manual legend with 1 value does not display correctly

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#246]
I have features which cover the entire AOI with a value of 1. When I create the manual legend, it displays like this:

![image](https://user-images.githubusercontent.com/29556279/191611254-a4041eec-4b9d-4e64-86a7-74b3540463f0.png)

**Comment by DanWismer** [comment]
For some reason, it is not treating that legend as an array:
![image](https://user-images.githubusercontent.com/29556279/191771628-32429a39-7dcd-4c6d-ab6b-4dd061f60501.png)

**Comment by ricschuster** [comment]
Could it be related to the values stored in that dataset? Are the integers, characters, float?

**Comment by DanWismer** [comment]
In the console, I get warning messages as if it is creating the 1 value 1 colour 1 label manual legend as continuous:
![image](https://user-images.githubusercontent.com/29556279/191772913-adcbec55-0413-43d6-bf49-1063b865c002.png)

**Comment by ricschuster** [comment]
What's the range of values you have in the data?

**Comment by DanWismer** [comment]
There is only one value in the data which is 1. The layer covers the entire study area.

More of a prioritization theory question here:
If a species binary layer covers the entire study area, does it make sense to just drop it as we know what ever site selection there is, that species will be represented?

**Comment by ricschuster** [comment]
If there is only a values of 1 the legend should only have one value and not an array, unless I am missing something?

I would not drop the layer, because we might still want to set a goal for that species. Depending on the locations and distributions of other species, we still want to include some information on that species. It might lead to the line patterns you sometimes see, which is informative to tell the user they have not enough information in their data to make meaningful recommendations for priority places.

**Comment by DanWismer** [comment]
Good to know, as there are a few layers in this ECCC project that have species of full coverage which causes that line like output.

And yes, you are right, if there is only 1 value in the data, the legend should just show that 1 value with that 1 colour. However there is something up in the code which is treating the individual characters in the label as the classes with manual legend. For example, this data I use manual legend to specify value 1 label as presence. There is something in the JS I need to work through.

![image](https://user-images.githubusercontent.com/29556279/191781906-63ed04bd-cad6-4848-b0a6-7b393512fe1e.png)

**Comment by DanWismer** [comment]
Bingo! I had to force the values and colors into a JS array for data with only 1 value and 1 colour.

![image](https://user-images.githubusercontent.com/29556279/191792303-dfac67f8-f0f7-42fa-b5b1-58d1649e9485.png)
