### ISSUE TITLE
reduce memory footprint of theme, weight, include coverage calculations

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#247]
I recently realized that the code in prioritizr for calculating feature representation was wasteful in terms of memory, because it needelessly stored data in a regular sparse matrix format -- when a sparse matrix format could be used to reduce memory usage. It also seems like switching over to a sparse matrix format and using matrix multiplication operations also reduces run time too. So, I had a look at the relevant code in WTW and it seems similar code was used here too.

https://github.com/NCC-CNC/wheretowork/blob/fe5fb1f2825c9b31f4ae9324d1bd3ea25f389648/R/utils_spatial_misc.R#L168-L169

@DanWismer, I just wanted to flag this for you, since you're working on updating WTW for large datasets? To address this in WTW, you could adapt those LOC to follow prioritzr's new memory efficient code (see [here](https://github.com/prioritizr/prioritizr/blob/sparsefix/R/eval_feature_representation_summary.R#L299-L307)). Basically, something like this could work:

```
out <- Matrix::Matrix(x, byrow = TRUE, ncol = 1, nrow = length(x), sparse = TRUE)
out <- as.numeric(out %*% data) / Matrix::rowSums(data)
```

Please verify it works though - I haven't tested it :)

**Comment by DanWismer** [comment]
Amazing, nice work Jeff. I will make those changes.

**Comment by DanWismer** [comment]
I get an error on the example `calculate_coverage` with the new LOC:

`Error in out %*% data : 
Cholmod error 'A and B inner dimensions must match' at file ../MatrixOps/cholmod_ssmult.c, line 80`

**Comment by DanWismer** [comment]
```
# load dependency
library(Matrix)

# simulate solution values for 10 planning units
solution_values <- sample(c(0, 1), 10, replace = TRUE)

# simulate data for 5 features in those 10 planning units
feature_data <- as(matrix(runif(10 * 5), ncol = 10), "dgCMatrix")

# calculate coverage
calculate_coverage(solution_values, feature_data)
```

Where data:
![image](https://user-images.githubusercontent.com/29556279/192359081-0305a0f9-c0fd-4870-9181-aaba4cb052e3.png)

And `out <- Matrix::Matrix(x, byrow = TRUE, ncol = 1, nrow = length(x), sparse = TRUE)` :
![image](https://user-images.githubusercontent.com/29556279/192359278-4503107d-1642-41ea-9ed9-f22bb6959b4c.png)

**Comment by DanWismer** [comment]
I think it is the `out %*% data` causing the issue

**Comment by jeffreyhanson** [comment]
Ah yeah that's it. Sorry it should be `data %*% out` (not `out %*% data`).

**Comment by DanWismer** [comment]
Awesome, that worked - the example code now runs!  Will run a few more tests and update to production
