### ISSUE TITLE
potential speedup for rendering rasters?

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#254]
I stumbled across the `leafem::addGeoRaster()` function (see https://www.rdocumentation.org/packages/leafem/versions/0.2.0/topics/addGeoRaster) which claims to provide optimized rendering for large raster datasets. It would seem that it functions as a drop-in-replacement for `leaflet::addRasterImage()`, so using it should hopefully not be too tricky? When you get a chance @DanWismer, this might be worth looking into?

**Comment by DanWismer** [comment]
Was the pane argument native to `leaflet::addRasterImage` ?
https://github.com/NCC-CNC/wheretowork/blob/450e7e6815c276f829f6248a28f45e17b51c2c3b/R/class_Variable.R#L169-L179

**Comment by DanWismer** [comment]
I tried this, but it was mapping the rasters incorrectly.
