### ISSUE TITLE
Login Page 

### ISSUE THREAD

**Issue by kushalg-1212** [NCC-CNC/wheretowork#259]
Hello , 
I deployed this app using the standard docker procedure and works pretty perfectly 
Is there a way i get a little guidance on the login page as the app opens normally and when i see your online version it asks me to login  , 
Is is something that's not available publicly or i need to do some modifications 

Thanks

**Comment by DanWismer** [comment]
The online version uses ShinyProxy for user authentication to access other apps. We have some development apps that are password protected for certain users.

**Comment by jeffreyhanson** [comment]
I'm sorry, I don't really have that much experience with authentification stuff in ShinyProxy. I'd suggest posting an issue on the ShinyProxy repo (https://github.com/openanalytics/shinyproxy), maybe one of the developers there could help you?
