### ISSUE TITLE
custom tool tip description for each setting

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#263]
Currently all the tool tips for each setting are the same:
![image](https://user-images.githubusercontent.com/29556279/203103330-3c3ce10a-e94a-4dce-a9c1-c0ca9dbb8f44.png)

 It would be nice to have a custom description for each setting

**Comment by DanWismer** [comment]
@jeffreyhanson @ricschuster 

Could you provide me with a a short text description on these WTW settings?
1. Total area budget
2. Spatial clustering 

I will add that text as the setting parameter tool-tip to better inform the user.

**Comment by jeffreyhanson** [comment]
Sounds good! What about:

Total area budget: Specify a maximum percentage of the total area that should be selected in the solution. 

Spatial clustering: Specify how much effort that should be spent on promoting spatial clustering in the solution. When no budget is specified, this controls the extra amount of land -- above what is needed to meet the goals -- that should be selected to maximize spatial clustering (as a percentage). When a budget is specified, this controls the percentage of the total area budget that should be dedicated towards promoting spatial clustering.

**Comment by DanWismer** [comment]
Thanks Jeff! 

I am thinking of adding a new tool-tip attribute to the Parameters class where I can add these descriptions

**Comment by DanWismer** [comment]
I moved the toggle tool-tip to the left position and dynamical add the parameter setting tool-tip text in the `solutionSettings.js`

![image](https://user-images.githubusercontent.com/29556279/207936153-e0c00075-fff8-4ad3-9b30-f305f144f071.png)
