### ISSUE TITLE
typo on override setting

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#266]
![image](https://user-images.githubusercontent.com/29556279/206561144-993667a6-d09a-46e1-b49d-aa33961ee3a7.png)

@ricschuster @jeffreyhanson 

Can you think of a better name for "override includes"? Or are we good on this? Ideally, I will create a tooltip that better explains each setting.

**Comment by jeffreyhanson** [comment]
yeah I think that's fine, I think having a tooltip that adds more detail is a great idea. Also, I think override might have two r's?

**Comment by DanWismer** [comment]
fixed on #270
