### ISSUE TITLE
add logos to wheretowork

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#267]
- ECCC
- RBC
- NCC

I am thinking somewhere here:
![image](https://user-images.githubusercontent.com/29556279/207089361-6ca2ac43-d289-4f1b-b12d-7ca27e1823c7.png)

**Comment by DanWismer** [comment]
ah yes, how can I forget!

**Comment by DanWismer** [comment]
Here is my first go at it:
![image](https://user-images.githubusercontent.com/29556279/207116603-ffac46a8-3406-4785-9495-d081025e7eb1.png)
import modal width is now 500px wide.

Are we liking this or should there be some different styling? I put the NCC logo up top because its dimensions are different then the other 3

**Comment by ricschuster** [comment]
Thanks Dan!

What do you think about Carleton and NCC next to each other and then ECCC and RBC in a new line?
Maybe also with "Developed by:" and "Supported by:"

**Comment by ricschuster** [comment]
@josephrbennett what are your thoughts on this?

**Comment by DanWismer** [comment]
2nd go:
![image](https://user-images.githubusercontent.com/29556279/207126647-695ea055-853f-4d19-b88b-07a88238d62e.png)

The ECCC logo is tricky because there is a ton of white padding on it, so when I go to a new line it makes the import modal long

**Comment by ricschuster** [comment]
Thanks Dan!
We could try for a smaller ECCC logo as well if there is one (Same for NCC).

How about this for layout:

NCC    Carleton
ECCC  RBC

**Comment by DanWismer** [comment]
3rd go:
![image](https://user-images.githubusercontent.com/29556279/207138088-2f7bd1a1-44ef-47a9-997b-1959b9c61526.png)

**Comment by DanWismer** [comment]
4th go:
![image](https://user-images.githubusercontent.com/29556279/207441336-71ebb01f-3ed0-4c83-8613-67e0f04ba4c8.png)

**Comment by jeffreyhanson** [comment]
Nice!!!

**Comment by jeffreyhanson** [comment]
Not sure if feasible, but I wonder if the acknowledgements/credits could be put in a seperate panel below the data import panel? E.g., something like:

![image](https://user-images.githubusercontent.com/3610005/207444761-ed471e98-9f2a-4660-b65b-cc1c007560c4.png)

**Comment by josephrbennett** [comment]
Thanks! THis is looking good. I like Jeff's idea, but am happy with Dan's latest suggestion as well.

**Comment by ricschuster** [comment]
Interesting idea Jeff.
Part of the reason why we (or at least I) thought including this right in the 'data import panel' was that it would mean that its really obvious (and hard to hide) who created this and supported this work. If an acknowledgements panel could be fixed (i.e. can't scroll away or hide) that would be an option as well.

@DanWismer what do you think?

**Comment by DanWismer** [comment]
For now I will keep it as is (logos in data import panel). Sometime in the future I can come back to trying a separate acknowledgments panel to see how it would look with logos spread across one column at the bottom.
