### ISSUE TITLE
update github actions workflow to use the `v2` version

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#273]
warning message on `r-lib/actions/setup-r@v1` 
warning message on `r-lib/actions/setup-pandoc@v1` 
warning on `set-output` command being deprecated and disabled soon. Upgrade to using Environment Files

![image](https://user-images.githubusercontent.com/29556279/210429437-4f4be6fc-9a52-40b1-a804-89bf039b29f6.png)

https://github.com/r-lib/actions/tree/v2/examples

**Comment by DanWismer** [comment]
@jeffreyhanson 

Could you remind me on where these variables are declared in the `R-CMD-check-windows.yaml`?
`matrix.config.os`
`matrix.config.r`
`matrix.config.pkgs`

Were they sent somewhere in an environment variable?

**Comment by jeffreyhanson** [comment]
Yeah they are defined in the YAML file, see https://github.com/NCC-CNC/wheretowork/blob/master/.github/workflows/R-CMD-check-ubuntu.yaml#L25-L28.
