### ISSUE TITLE
download prioritization input values and parameter settings as a config.yaml file

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#274]
- For each optimization run, it would be good to have all the `New solution` input parameters logged and available for download.
- Even better is if we can provide the user an upload option to populate `New solution` inputs with previous input runs (**adding this as a separate issue**)

**Comment by DanWismer** [comment]
@jeffreyhanson , just wondering if you have any comments on the this PR:

I have it now where I save a .yaml of the input and setting configs:  https://github.com/NCC-CNC/wheretowork/blob/d66dccb487484f1f05e9abe26c64c26c1757cf92/R/server_export_data.R#L73-L115 

On solution download, the .yaml looks like this
[prioritization-2023-01-16.zip](https://github.com/NCC-CNC/wheretowork/files/10428735/prioritization-2023-01-16.zip)

**Comment by jeffreyhanson** [comment]
Awesome! Just I only had a quick look, but what do you think about using the `$export()` methods for the classes (e.g. see here for include class: https://github.com/NCC-CNC/wheretowork/blob/master/R/class_Include.R#L270-L280). These export methods are used when wirting the project YAML metadata file - so might be useful to use them here as well for consistency?

**Comment by DanWismer** [comment]
I forgot about those `$export()` methods. Printing them out, I see that the method would export more attributes then we would need (ex. units, legend type, colors, etc.).

What about if I add a new `$export` method on each `ThemeResults`, `WeightResults`, `IncludeResults` and `ExcludeResult` ? That way I can call those methods that are designed for pulling relevant attributes distinct to the input configs (name, status, goal, etc.)? 

Alternatively, I can use the   `$export()` on each `Theme` , `Weight`, `Include`, `Exclude` and `Parameter` class  as you mentioned, but then use some type of matching logic in the `server_export_data.R` script to build out the .yaml with attributes distinct to input configs?

**Comment by jeffreyhanson** [comment]
Sorry, just getting to this now. Yeah, you're right that the `$export()` method will export a lot of extra uneeded stuff (like legends stuff). I agree, I think having the solution file align well with the input.yaml file will be useful. This is because it might help make it easier to verify that the the config file a user has uploaded is indeed for the current project loaded in the app, and keeps things a bit simpler by not having an additional/different file format/structure?
