### ISSUE TITLE
Wheretowork in a posit connect server

### ISSUE THREAD

**Issue by XavierCLL** [NCC-CNC/wheretowork#284]
Hi all!

Before I try, I just wanted to ask if any of you have experience or know about setting up the Wheretowork tool on a Posit Connect server as a Shiny app, does the Wheretowork tool work on that kind of service? I know that Wheretowork is not a simple shiny app, it is very tricky with many dependencies...

Thanks,
Xavier

**Comment by jeffreyhanson** [comment]
Hi @XavierCLL ,

Yeah, I did try to have a demo version launched with Rstudio Connect ages ago (I'm assuming this was a previous version of Posit Connect), but it didn't really work. I think this was because the app required more RAM than the free tier resources provided. IIRC I used the rsconnect R package to do this. Does that help?

**Comment by XavierCLL** [comment]
Thanks so much @jeffreyhansonr, that helps! I just wanted to know before trying it, I'm going to try it with the same package with the latest version of posit connect, I hope it works.

**Comment by ricschuster** [comment]
@XavierCLL do they have a free Tier for Connect? One of the biggest 'problems' I always saw with Connect was the huge price tag, which never got this solution to a point where I could justify using it.

**Comment by XavierCLL** [comment]
Hi @ricschuster of course you are right, I also prefer to run it in a docker container inside a server you can manage (you have more control and independence). I asked about the posit connect because UNBC has a license on that and Oscar is using the tool for his classes, so I think in this case that is a good option.

**Comment by ricschuster** [comment]
Great to hear that UNBC has a license. That might make sense in this case, although having a similar setup to what we have here (ncc.carleton.ca) with ShinyProxy would also work well for that use case I think.
