### ISSUE TITLE
add indication to the user that solution setting was updated

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#287]
currently, toggles and sliders update without letting the user know #285

**Comment by DanWismer** [comment]
big yaml files take a longer time to load in on the server cause a delay in the icon colour ...

**Comment by ricschuster** [comment]
If a yaml file has been loaded one needs to clear it by clicking 'cancel' in the `Choose File` pop up. It would be great if this step would not be necessary.

**Comment by ricschuster** [comment]
What do you think about displaying some meta data after the yaml file has been uploaded?
Something like author name and date. Maybe something else too, but I'm not sure.

**Comment by ricschuster** [comment]
Should toggling off `Update solution settings` remove the yaml and turn the icon grey?

**Comment by ricschuster** [comment]
Tooltip stays up/active after file is uploaded. 
It disappears on other items.

**Comment by DanWismer** [comment]
> If a yaml file has been loaded one needs to clear it by clicking 'cancel' in the `Choose File` pop up. It would be great if this step would not be necessary.

That's a good point. Cancel clears the file, however with the current set up the user can update the .yaml without clearing it. Instead it just updates it. I think this is how the import modals work as well on the welcome page.

**Comment by DanWismer** [comment]
> What do you think about displaying some meta data after the yaml file has been uploaded? Something like author name and date. Maybe something else too, but I'm not sure.

I like this idea. At minimum I could add that info to the tooltip? Or we could think of a spot on the UI to add that info

**Comment by DanWismer** [comment]
> Should toggling off `Update solution settings` remove the yaml and turn the icon grey?

I am not sure ... the toggle for this only just hides/shows the setting. It doesn't modify behavior like the other settings do. The tricky thing is if the user toggles off the setting, what should happen to all the new solution values? Reset to the original? Do nothing?

**Comment by DanWismer** [comment]
> Tooltip stays up/active after file is uploaded. It disappears on other items.

I updated the code so the behavior is better by updating the file icon colors on the server once the data is passed to R. There are 3 states to the file icon: grey == no file, green == success and red == unsuccessful. I also had to add: set the `priority: "event"`  https://github.com/NCC-CNC/wheretowork/blob/fca6907f151a811748eda0e9c1d4c3f4446f38ac/inst/htmlwidgets/lib/solutionSettings-1.0.0/ParameterSetting-class.js#L184-L189
https://shiny.rstudio.com/articles/communicating-with-js.html 

This should be working better now., but I think could still be improved on

**Comment by DanWismer** [comment]
Will close this for now. Any new edits to this will be on a new issue/PR
