### ISSUE TITLE
download/export behavior is inconsistent with large projects like BC CMC

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#295]
Cindy has reported that the download solution hangs and never ends up downloading. I have experienced the same, but it is not consistent.

**Comment by DanWismer** [comment]
Maybe?
https://support.openanalytics.eu/t/shiny-app-downloadhandler-timeout/2234

**Comment by DanWismer** [comment]
@ricschuster I am wondering if it has to do with the nginx.conf?

https://github.com/rstudio/shiny-server/issues/197#issuecomment-721411595

**Comment by ricschuster** [comment]
Could be. I just did a couple of test runs and the results are actually small zip files (<200kB):
[prioritization-2023-03-02 (1).zip](https://github.com/NCC-CNC/wheretowork/files/10876446/prioritization-2023-03-02.1.zip)

Its a bit puzzling to me.

**Comment by DanWismer** [comment]
We were able to get WTW to run locally on Cindy's computer. The solution ran and downloaded locally. 

I figure this must be a server thing ...

**Comment by DanWismer** [comment]
I got the download to work on the dev server: https://github.com/NCC-CNC/wheretowork/issues/316#issuecomment-1771618447

**Comment by DanWismer** [comment]
ssl time out. case closed!
