### ISSUE TITLE
new_dataset_from_auto: Error: cannot allocate vector of size 62.9 Gb

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#301]
@jeffreyhanson, I am pushing the boundaries on how big of a project WTW data formatting can handle. I am getting Error: cannot allocate vector of size 62.9 Gb, when I get to https://github.com/NCC-CNC/wheretowork/blob/1a5bed34b9ba29be2749b8d49520a5a7e9b12220/inst/scripts/format-south-western-ontario-data.R#L123-L125 

The allocate error happens here: https://github.com/NCC-CNC/wheretowork/blob/1a5bed34b9ba29be2749b8d49520a5a7e9b12220/R/class_Dataset.R#L658 

I am wondering if you had any ideas on how to get around this? Something with `rasterOptions` ?

**Comment by ricschuster** [comment]
@DanWismer you could try `rasterOptions` with something like this:

```
raster::rasterOptions(tmpdir = here::here("tmpdir"),
                      maxmemory = 1e+11, #100GB
                      chunksize = 1e+10 #10GB
)
```

**Comment by jeffreyhanson** [comment]
Hmm, you might be able to optimize the code to reduce memory by doing something like this to replace these lines (https://github.com/NCC-CNC/wheretowork/blob/1a5bed34b9ba29be2749b8d49520a5a7e9b12220/R/class_Dataset.R#L658-L663):

```
pu_idx <- raster::Which(sum(is.na(x)) < 0.5, cells = TRUE)
attribute_data <- tibble::as_tibble(as.data.frame(x[pu_idx]))
attribute_data <- dplyr::select_if(attribute_data, is.numeric)
attribute_data[["_index"]] <-  pu_idx
```

However, it would be slower than the current implementation for smaller sized datasets.

**Comment by DanWismer** [comment]
hmm what's odd is the BC_CMC project I never got this allocation error. That project has 1002 layers with 139,675 1km2 PUs ...

I am getting an error on a NB project that has only 385 layers with 74,848 1km2 PUs

**Comment by ricschuster** [comment]
So the NB project is not at the 10ha scale?

**Comment by DanWismer** [comment]
The NB project I passed to Pat and Eleanor are at the 10ha scale. I did a separate NB 1km as a demo for showing Marc how to format data to WTW files

**Comment by ricschuster** [comment]
That is odd.

**Comment by DanWismer** [comment]
... I think I know my issue! Will test it tm, but I created a new workflow for generating the AOI:
https://github.com/NCC-CNC/aoi-to-1km-grid/blob/main/R/aoi_to_1km_grid.R

This is creating all the raster layers with 5700 columns and 4700 rows! That is the extent of that constant grid.

**Comment by DanWismer** [comment]
ok  we are back in Biz., I fudged up the AOI.tif and gave it the same extent as our NCC constant grid (4700 rows, 5700 cols, 26790000 cells). That led to every national layers being "clipped" to that massive extent. 

will close this
