### ISSUE TITLE
Gurobi Solver

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#302]
https://www.gurobi.com/solutions/gurobi-instant-cloud/

**Comment by DanWismer** [comment]
@ricschuster  @edwardsmarc does your license look like this?

![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/79e3582a-8060-46b3-8fd9-98250df2751d)

I am confused on the  Type `Single-Use`. I thought it would specify cloud? My understanding of single-use is that the license is then tied to a specific machine?

**Comment by edwardsmarc** [comment]
I guess I was expecting it to show up in the WLS manager, but there's nothing in there either. Based on the email chain we should be getting WLS single-use which they described as being specific to a single container at one time.

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/e2da4efd-61a1-4d50-902d-0c6d2ccc1552)

**Comment by DanWismer** [comment]
I have downloaded the gurboi.lic:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/4dec1ed2-3b1f-4274-ab99-a5fd7b2b88f9)

I checked out the file and it has:
- WLSACCESSID
-  WLSSECRET
- LICENSEID

And I have placed the file in `C:\gurobi`

I am at the [testing](https://www.gurobi.com/documentation/current/quickstart_windows/testing_your_license.html#subsection:testlicense) section. 

When I open up: 
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/26b4073a-c385-43ed-9868-bf150474884a)

I get:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/f598f6d2-9b54-447a-af59-da8b8599d6ec)

I am wondering ... do I have the wrong Gurboi software installed? @edwardsmarc is your Windows desktop gurboi called `Gurboi token server`?

**Comment by DanWismer** [comment]
ohhh... I see there is a:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/4d6900ef-c10c-498b-b0ad-adc5fb0ada08)

I think we are in the clear:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/61560f66-6905-4c89-ade4-3bfc7d0586c6)

**Comment by DanWismer** [comment]
It works!!

```
library(gurobi)

# create optimization problem
model <- list()
model$obj        <- c(1, 1, 2)
model$modelsense <- "max"
model$rhs        <- c(4, 1)
model$sense      <- c("<", ">")
model$vtype      <- "B"
model$A          <- matrix(c(1, 2, 3, 1, 1, 0), nrow = 2, ncol = 3,
                           byrow = TRUE)

# solve the optimization problem using Gurobi
result <- gurobi(model, list())
```
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/76e75395-dd15-4262-947f-d9a3968c249e)

I can also see activity now on our Web License Manager

**Comment by DanWismer** [comment]
This is the error if the license is in use:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/71123930-b9ba-48ac-8ec1-bd75b2701eb8)

**Comment by edwardsmarc** [comment]
Awesome! Great work @DanWismer.

Looks like we can easily catch that error and decide what to do with it.

**Comment by DanWismer** [comment]
@jeffreyhanson, how should I handle the `gurobi` package with renv? I added it as a Suggests in the DESCIPTION file and also update the renv.lock file with it. However, when I do `docker-compose up --build -d` I get an error because it is trying to download `gurobi` via CRAN

![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/5e7592fa-7831-4c5b-b15a-568d8ca49deb)

**Comment by jeffreyhanson** [comment]
Since the gurobi package isn't on CRAN, you'll need to (1) tell renv to ignore it so that renv doesn't try to install it, and (2) update the install code to manually install it. To do (1), you'll need to chage the `renv/settings.dcf` so that it has gurobi in the ignored packages. Here's an example file from one of my projects:

```
bioconductor.version:
external.libraries:
ignored.packages: gurobi
package.dependency.fields: Imports, Depends, LinkingTo
r.version: 4.1.2
snapshot.type: implicit
use.cache: TRUE
vcs.ignore.cellar: TRUE
vcs.ignore.library: TRUE
vcs.ignore.local: TRUE
```

**Comment by DanWismer** [comment]
I will give that a try, thanks! Should I remove gurobi from from the renv.lock file?

**Comment by DanWismer** [comment]
I ask because when I updated the renv/settings.dcf file, I get this now:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/78844664-b9c7-4479-a7fe-b513968d6772)

**Comment by DanWismer** [comment]
> 

how do I go about manually installing it? That would be in the dockerfile?

**Comment by jeffreyhanson** [comment]
Yeah, I'd remove gurobi from lock file. 

Yeah, I'd put the code for installing it in the dockerfile. E.g., have it runs some R code that looks like this:

```
renv::install(
  dir(
    paste0(Sys.getenv("GUROBI_HOME"), "/R"), "^.*\\.tar\\.gz",
    full.names = TRUE
  )
)
```

**Comment by DanWismer** [comment]
I added line 36 to the dockerfile:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/6caebd56-8ff5-4097-ab6c-fda0925a9ca4)

When I build the image and launch the container, I am still getting the message in the logs that gurobi is missing:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/5929d350-30fb-4776-8f90-868c6df11b87)


Could I make a copy of the `C:\gurobi1002\win64\R\gurobi_10.0-2.zip` and have it in the root WTW dir? That way it would ship with the package? And maybe be easier to install?

**Comment by DanWismer** [comment]
I found this:
https://github.com/AEADataEditor/docker-r-gurobi

**Comment by DanWismer** [comment]
now that I think about it... do we need to have gurobi software installed in the container? Ideally not. I assume its possible for an app inside a docker container to talk to software (gurobi), that lives on the host?

**Comment by ricschuster** [comment]
I don't think we need Gurobi installed in the container. Both Gurobi and license can be on the server.

**Comment by DanWismer** [comment]
Excellent, I emailed Jennifer to confirm. I ask because in that dockerfile I linked, he has the license file and the gurobi software in the image

**Comment by ricschuster** [comment]
We should definately not have the license file in the image.

**Comment by ricschuster** [comment]
That would allow anyone to use the Gurobi license we have.

**Comment by DanWismer** [comment]
ah ha! RE container: I have been working with the folks at Gurobi to help get this figured out.

@jeffreyhanson check out my last commit: https://github.com/NCC-CNC/wheretowork/commit/1e3c94154b6d818f3a40d0199e6c7539f13fe812

There is no GRB_LICENSE_FILE variable set in .env, and rather the location is mounted in dockerfile volume. Also there was some other formatting things we needed with the strings.

**Comment by jeffreyhanson** [comment]
Awesome!

**Comment by DanWismer** [comment]
So we CAN set the license file path in the .env, however we need to call it something else other then GRB_LICENSE_FILE:
https://github.com/NCC-CNC/wheretowork/commit/ee390cc876861e7831310d6027a09903ac1eab57

This is working. 

Now the next challenge will be to get this to work using web-apps repo and the docker swarm/shinyproxy config

**Comment by DanWismer** [comment]
adding some communication I have had with a Gurobi rep for documentation:

We highly recommend placing the Gurobi license file in one of the default locations because it is less error-prone. Setting the environment variable GRB_LICENSE_FILE is necessary if the license file is placed in a non-default location.
 
We mounted the license file in the /opt/gurobi/ directory which is a default location for the Gurobi license file in linux (see the article [Where do I place the Gurobi license file (gurobi.lic)?](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.gurobi.com%2Fhc%2Fen-us%2Farticles%2F360013417211-Where-do-I-place-the-Gurobi-license-file-gurobi-lic-&data=05%7C01%7CDan.Wismer%40natureconservancy.ca%7C174a762786234474f64d08dbafc90bc7%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C638297050255191813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QTHCK%2Bi2OyCvh4gpQnjwefGh%2Bga5oFj2klBetYvySFc%3D&reserved=0)) and Gurobi will see it because this is one of the locations it expects to see the license file. Therefore, there is no need to set the GRB_LICENSE_FILE variable.
 
Having GRB_LICENSE_FILE="C:/gurobi/gurobi.lic" is wrong. My understanding is that these variables are sent to the container. Since there is no license at C:/gurobi/gurobi.lic inside the container, Gurobi gets confused.

**Comment by DanWismer** [comment]
I was able to get gurobi to work when launching from the web-apps repo: https://github.com/NCC-CNC/web-apps/compare/master...30-gurobi

The problem now is that at the end of the run, it is not releasing the license. @jeffreyhanson I vaguely recall that you mentioned that we may have to explicitly stop the solver because sometimes it just keeps going? However, thats only under the context if a users uses the stop button?

**Comment by DanWismer** [comment]
I am also getting this error now:
Timing stopped at: 0.043 0.022 1.993
[1] "Error 10030: Too many sessions, 1 active sessions for a baseline of 1\n"

**Comment by jeffreyhanson** [comment]
Yeah, if you use the stop button, then the solver will just keep on running so I don't think it would relinquish the license. So, you might have to come up with some way to kill the gurobi solver? I don't really know how to do this. This issue might have some ideas (https://github.com/HenrikBengtsson/future/issues/93), or maybe the async code could be rewritten to use another package instead? E.g., the crew package seems to be able to terminate workers (https://wlandau.github.io/crew/).

**Comment by DanWismer** [comment]
I am noticing quite a difference with solutions between gurobi and cbc:

cbc:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/ce6fc895-5fad-4f67-962b-ed88054ec9fd)

gurobi:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/b12f2588-a339-4c7e-beb0-bb43581b317d)

Any ideas why this is the case?
