### ISSUE TITLE
replace RandomFields

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#307]
[RandomFields](https://cran.r-project.org/web/packages/RandomFields/index.html) has been booted off CRAN for sometime now ( [Archive ](https://cran.r-project.org/src/contrib/Archive/RandomFields/)).

Will look at using `prioritizr` simulate data functions for our tests as a replacement: https://github.com/prioritizr/prioritizr/blob/main/R/simulate.R

**Comment by DanWismer** [comment]
I am starting to look into how I can go about simulating data without using Random Fields. 

I need to convert the following [simulate_spatial_data](https://github.com/NCC-CNC/wheretowork/blob/master/R/fct_simulate_spatial_data.R) functions:
1. simulate_proportion_spatial_data, values are between 0-1 (decimals allowed)? 
2. simulate_continuous_spatial_data, values are between 1-100 (decimals allowed)?
3. simulate_categorical_spatial_data, values are between 1-9 (no decimals)? 
4. simulate_binary_spatial_data, values are 1 or 0 (no decimals)
5. simulate_spatial_data
6. simulate_random_field

**Comment by DanWismer** [comment]
I think I can use the new [simulate_data](https://github.com/prioritizr/prioritizr/blob/main/R/simulate.R) function which uses the [fields](https://cran.r-project.org/web/packages/fields/fields.pdf) package.

Nice thing is that there is a `transform` argument where I can use the already written transformations to create categorical and binary data.

**Comment by DanWismer** [comment]
@jeffreyhanson @edwardsmarc @ricschuster 

for package development, how do you handle `Warning: package 'x' was built under R version y` ?

**Comment by DanWismer** [comment]
... looks like we can ignore this warning, otherwise I can bring the R version up to 4.1.3

https://stackoverflow.com/questions/27395777/creating-r-package-warning-package-was-built-under-r-version-3-1-2

**Comment by edwardsmarc** [comment]
@DanWismer - that stackoverflow response summarizes my understanding of it. It's a warning we should be aware of but it won't break anything unless `raster` behavior changes in R 4.2.1.
