### ISSUE TITLE
convert raster to terra

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#315]

**Comment by DanWismer** [comment]
@ricschuster I should probably get on this one. I am hoping that doing this will also improve performance.

**Comment by ricschuster** [comment]
Agreed. Would be good to move to terra.

**Comment by DanWismer** [comment]
Hmm was wanting up updated the terra package to 1.7-78 but getting this weird error:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/14c216fb-9a02-4b62-890b-656335dec03b)

@jeffreyhanson have you seen this before?

**Comment by jeffreyhanson** [comment]
Sorry, I missed this earlier. Were you able to resolve this issue?

**Comment by DanWismer** [comment]
We are currently using a forked version of leaflet which is on version `2.0.3.9000`. It wasn't until leaflet version `2.2.0` that it supported terra. I am at a spot where addRasterImage fails to add SpatRasters:

 https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/class_Variable.R#L169-L179
 
 @jeffreyhanson, is it possible to update the forked version of leaflet to its most current version `2.2.2`? And if so, what would be the best way to do that?

**Comment by jeffreyhanson** [comment]
Yeah, the forked version of leaflet is here (https://github.com/NCC-CNC/leaflet/tree/pane-extra). I would suggest re-forking the latest version of leaflet, and then addding in the changes present in the fork again (see https://github.com/NCC-CNC/leaflet/commit/7210a3a1924d2b23a3571bc5f6f38eb11b128fc3). How does that sound?

**Comment by DanWismer** [comment]
PR #380
