### ISSUE TITLE
solution table view not displaying

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#316]
On some WTW NB 10ha project runs, the table view does not display. The download doesn't work as well ...

![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/49c07008-37c0-46cd-b75e-0c5ad2cec6fd)

**Comment by DanWismer** [comment]
I am seeing this error in the console:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/8ee3c34b-04b4-4fa7-9d59-7c4897acabcc)

@ricschuster, do you recall if the Carleton server is using HTTP or HTTPS protocols? 

When I go to inspect the table body, the html is completly empy:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/3401550a-a8ec-4021-a392-1de6495ed64a)

... I wonder if this HTTP vs HTTPS has something to do with it?
https://stackoverflow.com/questions/67765238/mixed-content-the-page-at-was-loaded-over-https-but-requested-an-insecure-resour

**Comment by DanWismer** [comment]
insecure XMLHttpRequest endpoint:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/119ac025-4f12-4ddc-a8ec-3f929d96a3d1)

**Comment by DanWismer** [comment]
checking out the network tab I am getting this `status code of 302` on the solution results modal:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/3bf54bd3-ced4-44be-a784-fe8c55c97edd)

**Comment by DanWismer** [comment]
Interesting, I tried the 15% budget again and got this error in the console:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/009194bc-bf7a-46ca-a57c-9023c5905366)

**Comment by edwardsmarc** [comment]
I'm getting the same issue using a large project in BC:

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/fad26ca3-9bc0-4e11-8f63-ce2da0689a72)

**Comment by edwardsmarc** [comment]
For my BC project, the problem runs in <10mins on my local version of WTW, but after 2-3 hours of processing on the server it returns a strange solution and the above errors. You can see in the solution below, the result has unusual patterning on the southern border, and the final solution when using a 30% area budget only covers 22% of the AOI. The min_set solution requires 51% of the planning units to meet all targets, and when run locally the 30% area budget using 30% of the planning units. This 22% solution is completely different to the solution I get locally.

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/f55bbd09-5473-4307-827b-001390988cc2)

**Comment by edwardsmarc** [comment]
A quick check of the shiny log files on the server for some of these runs does not reveal any warnings or messages. They are mostly empty, which actually makes me wonder if we should make the app more verbose. It might be useful to have the solver output in the log file for example. Currently the calls to prioritizr are wrapped in try(silent = TRUE).

**Comment by DanWismer** [comment]
Thanks for checking the server logs Marc. If I recall, if it errors in the `try` statement, the error message will be captured and printed to a pop-up modal. However, it won't catch warnings if there are any. We could try seeing if we could output on the server. To be safe, we should get to setting up the dev server and have it listen to a dev branch. That way we can do way more experiments / trial and error and not worry about breaking prod.

**Comment by ricschuster** [comment]
I'm a big fan of setting up the dev server. Let me know if there is anything I can help with.

**Comment by DanWismer** [comment]
in the `<head>`:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/7be7833e-07b7-4485-9781-97e6782c614a)

then in the `iframe` (I beleive this is a shiny proxy thing... places entire app inside an iframe tag)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/4f618461-65fe-438d-bbfa-0a23be45b595)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/3c3982a2-f5b1-446d-bcca-271203f25b61)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/987c0924-3307-47ed-9056-b80dbae4847f)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/1b561b4d-2a3e-439c-9a4b-d6358f4b3270)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/424f6a22-5fae-4f5a-841a-8074e249eddb)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/e1532ef7-5731-4219-9419-97360e2afc8d)

**Comment by DanWismer** [comment]
When I do a default run on the first try, I get no error. Then when I go for the 15% budget on the second run, the only error I see in the console is: 
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/bae5ca24-2173-4546-98f8-ce9de1c942c7)
And the table looks like this:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/89b447f9-f655-4920-8ee5-fdd95f2ca36c)


This is different from when you run the 15% budget on the first run. You get more errors ...

**Comment by DanWismer** [comment]
Interesting, this warning is shown on every instance of WTW via Sites:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/156d7fcc-4286-44fa-b60c-69fd3fe703a5)

**Comment by DanWismer** [comment]
This is a shot in the dark, but I am wondering if we need to update our shiny version and DT version. My gut is thinking there is outdated `jquery.min` libraries being used that is not being handled by modern browsers ...

**Comment by edwardsmarc** [comment]
@DanWismer I was just talking to Richard about this and another thing to try would be updating the linux software on the server. He said he could help with this if we're not confident doing it ourselves.

**Comment by DanWismer** [comment]
Worth a shot, is there any indication why it may be a linux server thing?

I am wondering if updating our meta tag would do the trick
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

 https://stackoverflow.com/questions/33507566/mixed-content-blocked-when-running-an-http-ajax-operation-in-an-https-page

**Comment by DanWismer** [comment]
@ricschuster do you recall if the server is set up to use HTTP or HTTPS protocols? By default I think shiny proxy uses HTTP? When I go to the security tab it says that this page is secured (valid HTTPS)
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/41fc2fe5-138a-4209-bdcb-83805536fa16)

**Comment by DanWismer** [comment]
... It must be https as thats whats in the address:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/ed7dc701-2d44-4e43-9cc2-78ac26d52636)
 
 So my guess is that some content coming from DT for some reason is using HTTP? which is getting blocked by the client

**Comment by edwardsmarc** [comment]
> Worth a shot, is there any indication why it may be a linux server thing?
> 
> I am wondering if updating our meta tag would do the trick `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
> 
> https://stackoverflow.com/questions/33507566/mixed-content-blocked-when-running-an-http-ajax-operation-in-an-https-page

No indication. We were just noticing that the server has not been updated for a while.

**Comment by ricschuster** [comment]
Just updated the server. See if that makes any difference.

**Comment by DanWismer** [comment]
Thanks @ricschuster 

bummer, I am still getting the same errors and no table / download not working.

**Comment by DanWismer** [comment]
confirmed that the download and table errors do not occur when running locally.

Next week I will try adding `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` and see if that fixes the mixed content error

**Comment by DanWismer** [comment]
I am wondering if this needs to be addressed: 

https://github.com/NCC-CNC/web-apps/blob/e1728814decfaa8c54d2e2580cb18720170d4a91/web-apps-nginx.conf#L26

Tips on fixing mixed content, find all the calls to `http` in the source code:
https://web.dev/fixing-mixed-content/#alternatives_to_csp

The "mixed content" error are originating from `http://ncc.carleton.ca/login`
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/f03c8671-0df3-43dc-b244-47abc67df086)

**Comment by DanWismer** [comment]
Firefox:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/ecf88a8a-d1ce-47f1-b323-f8ff203f11ca)

**Comment by DanWismer** [comment]
Checked the docker container log on the server, nothing to report:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/ab34a506-78d4-4a94-a5a5-0981fbc4e41f)

**Comment by DanWismer** [comment]
I found that there are NGINX error logs on the Prod server:
`/var/log/nginx`

@jeffreyhanson @ricschuster, how do I view these files on linux?
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/f2cc5839-7398-4c6a-b1af-99b85c844c10)

**Comment by ricschuster** [comment]
> Thanks Richard.
> 
> We have a failed handshake ??
> 
> ![image](https://user-images.githubusercontent.com/29556279/242344418-809dad82-d998-456f-abb9-8bf076fca8d9.png)

I have no idea what that might indicate. Maybe this is something to ask the IT folks at Carleton. What do you think?

**Comment by ricschuster** [comment]
> I see that NGINX on Prod is `1.18.0` The latest stable release is `1.24.0`

Did you update the NGINX version yet? We could update and see what that does.

**Comment by DanWismer** [comment]
This is interesting... 

On the dev server I made it to 
```
# restart web server for configuration to take effect
sudo systemctl restart nginx
```
Where it didn't work. I then tried this to get some diagnostics:
```
sudo systemctl status nginx.service
``` 
And the message:

![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/d6baa76e-8c52-4d24-b62a-8f37b4a67280)


Long story short ... I wonder if our `ssl_certificates` are old? If thats even a thing ...

**Comment by DanWismer** [comment]
I am readding that the `proxy_redirect` set to `off` can potentially create those **Mixed Content** errors.

@ricschuster is there a reason why we have it configured to off?
https://github.com/NCC-CNC/web-apps/blob/e1728814decfaa8c54d2e2580cb18720170d4a91/web-apps-nginx.conf#L34

**Comment by ricschuster** [comment]
Not that I know of. I don't recall touching that parameter.

**Comment by DanWismer** [comment]
On the dev server, the first error in the console is:

`Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

This in turn creates a **SyntaxError** when reading the ShinyProxy sign-in html:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/800d92fb-6e81-4324-af36-d81eb24b1a44)

I read that I can add `include mime.types;` in the **nginx.config**. Will give that a try ...

**Comment by DanWismer** [comment]
This is what the Network tab looks like when the tables work

 
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/c87f06ea-a107-4dd4-8d94-2ba713c56222)

**Comment by DanWismer** [comment]
will try updating the DT package
https://github.com/rstudio/DT/releases

**Comment by jeffreyhanson** [comment]
Not sure what the status on this issue is, but I just stumbled across this newer package for rendering tables (https://github.com/glin/reactable/). It seems to provide all the functionality needed for rendering the tables in WTW (e.g., displaying icons, updating values in table, download CSV options). So might be worth looking into if this bug is still causing issues?

**Comment by DanWismer** [comment]
Nothing new here. I gave up after a lot of different attempts.

Going to `reactable` I think would be worth it. Even DT author says if reat table was around in 2015 he would not have created DT: https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html

**Comment by jeffreyhanson** [comment]
Ah ok. Ooh, that's interesting about DT vs. reactable.

**Comment by DanWismer** [comment]
What if we try copying the DT JS files like it is done for shinyBS? I am wondering if this whole time it has been a container issue?
https://github.com/NCC-CNC/wheretowork/blob/201567df0a0004bc80868ba808288a9ed58f266e/R/app_ui.R#L23-L24

@jeffreyhanson, what do you think?

**Comment by DanWismer** [comment]
ah ha! I ran WTW inside the web-apps repo on my local, and the tables are not showing here:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/d5109642-b6b8-42d0-a5e0-36481958cebb)

This makes me believe that there is indeed something up with the container. I also ran the WTW container from the wheretowork repo and the tables **did** show. So I think I have isolated the issue down to the web-apps repo, and something to do with docker?

**Comment by DanWismer** [comment]
this is the new JS error: `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by DanWismer** [comment]
Checked the docker log on the server and I see this:
`org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "%25"`

opened up a thread on the community support: https://support.openanalytics.eu/t/the-request-was-rejected-because-the-url-contained-a-potentially-malicious-string-25/2627

**Comment by jeffreyhanson** [comment]
Oooh - interesting! Yeah, maybe serving a copy of the JS (similar to shinyBS) might fix this? I dunno sorry. Great idea posting the thread on community support - maybe someone there will have some ideas?

**Comment by DanWismer** [comment]
I have another hunch on the tables and downloads not viewing on long runs.

I have been researching this nginx config:
https://github.com/NCC-CNC/web-apps/blob/e0d654e3c13223febb964ec3a3ba5a7e21a4ecf7/web-apps-nginx.conf#L14

What I am reading is that the app session parameters will expire after 10 minutes. I think what might be happening is that the user's session times out, which affects the security parameters. This is why we get the bad handshake error when there is a request from the client back to the server (i.e. view a table output or download a WTW out
put after a long run)

**Comment by DanWismer** [comment]
Fairly confident that its that `ssl_session_timeout 10m; ` nginx config. I tested by doing a default run with the SW Ontario project, then not touching the app for over 10 mins. Then I tried downloading and it re directs me back to the sign-in page.

**Comment by jeffreyhanson** [comment]
Awesome - brilliant working solving that @DanWismer!! 

No idea sorry. Yeah those seem pretty reasonable.

**Comment by DanWismer** [comment]
Thanks everyone! I went with 1day on prod, 3 days on dev. We can change this to something else down the road. case closed!
