### ISSUE TITLE
remove sensitive layers defined by the project author from being downloadable 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#319]

**Comment by ricschuster** [comment]
That's a good one. 
How hard do you estimate would it be to implement that?

**Comment by DanWismer** [comment]
It would require adding a new config that captures non-downloadable layers in the .yaml file. Then on import, I would need to remove those layers explicitly defined from the available download choices.  

Two weeks or under I could get this built into production. 

For all current projects, I am not 100% sure what the best approach would be in order to update their .yaml. Probably just editing it directly. Otherwise, for all new projects, it would be a new required column in the metadata.csv.

**Comment by ricschuster** [comment]
Sounds reasonable to me.

Do you have a sense of where that would fall on your priority list?

**Comment by DanWismer** [comment]
somewhere in the middle. I am told NB has sensitive layers, plus nationally all our NSC data. For NB, they are working with groups outside of NCC which do not have DSA for certain layers we have received.

**Comment by DanWismer** [comment]
after some thought ... 

instead of creating an additional attribute in the .yaml that defines if the layer should not be downloadable. It may be best to use the already built-in `hidden` attribute and make an assumption for the user that if they want it hidden from the map, then that also makes the layer unavailable for download. Before lazy-loading this would have been a problem, but now I think this would be OK.

**Comment by DanWismer** [comment]
@ricschuster @jeffreyhanson @edwardsmarc 
I will be working on this feature so we do not expose sensitive cultural layers. 

Will create a new `download` attribute set to `TRUE` or `FALSE` for Themes, Weights, Includes and Excludes. Then on data prep, for each layer, you can decide if the layer should be exposed to download or not.

**Comment by ricschuster** [comment]
Awesome! I really like this feature idea.

**Comment by jeffreyhanson** [comment]
Sounds great to me!

**Comment by DanWismer** [comment]
PR #394
