### ISSUE TITLE
Area budget - unexpected solutions

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#321]
## Problem
We've had examples in BC where planners are running WTW with increasing area budgets from 5% to 30%. The solutions are not always nested. The expectation from users is that all PUs identified in a 5% or 10% run should be those holding the most valuable habitat, and they expect those PUs to show up in all other runs with increasing area budgets. This is not always the case. 

Note: In the BC example, there could be multiple things going on, see my comment in [#316](https://github.com/NCC-CNC/wheretowork/issues/316#issuecomment-1550409965) outlining some unexpected behavior on the server. Ignoring this potential issue, the question is: **is this non-nested behavior expected based on how min_shortfall_objective() works in prioritizr?**

Below is an example from the BC project that has ~900 targets (no weights, includes or excludes). The total budget required to meet all targets is ~55%. Note how some clustered areas selected at 10% are removed at 20%. Also note that I don't think this is an optimality gap issue, I tried lowering it and found the same pattern.
![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/3734247d-024b-4815-aaf0-4f01d57912df)

## Solution
Based on my understanding of min_shortfall_objective() (minimise the summed proportion of missing targets), this behavior is not unexpected for the following reasons:
- When many targets cannot be met with the available budget, it makes sense to prioritize the areas of highest overlap, accepting that some targets will be completely missed. See the first solution in the diagram below.
- As area budget increases, the most efficient solution will not necessarily include the areas of highest overlap, because shortfall can be minimized by selecting multiple other areas of lower total overlap. See the third solution in the diagram below.
- A very simple example of this is shown in the diagram below, where the bottom left PU has the highest overlap, but is not included in optimal solution that meets all targets.
  - Note that there are many 2PU solutions that meet 4 targets, I've just included one example
  - The important point is that there are no 3PU solutions that include the bottom left PU and meet all targets

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/ad6d727e-fbaa-4e24-bbac-e5fa74eafdde)

**Comment by DanWismer** [comment]
Nice visuals Marc!

So as area budget increases, solutions will not necessarily be nested because the min shortfall is optimizing to select the most amount of unique species. Using your example, the bottom left PU has the most overlap, however at a 3 PU area budget, that PU is not selected because it doesn't optimally cover the most amount of unique species given the budget?

**Comment by edwardsmarc** [comment]
> Nice visuals Marc!
> 
> So as area budget increases, solutions will not necessarily be nested because the min shortfall is optimizing to select the most amount of unique species. Using your example, the bottom left PU has the most overlap, however at a 3 PU area budget, that PU is not selected because it doesn't optimally cover the most amount of unique species given the budget?

Exactly! Especially if the species found in those areas of highest overlap also have habitat elsewhere that can be picked up. I think having binary species ranges might also contribute to this. If the habitat maps were continuous then it might force it to focus on the PUs with highest values.

And just so we're on the same page, min_shortfall is not trying to cover the most species, it's trying to minimize the total amount of 'missed targets'. In my simple example it's the same thing sine all my targets are 1 pu, but in a real example it calculates the proportion of each target not met, and tries to minimize the sum of those values.

**Comment by ricschuster** [comment]
Thanks very much for putting this all together @edwardsmarc!
This is great stuff!

Given what the min_shortfall objective function is doing, we could also think about whether min_shortfall is the 'right' objective function for our purposes.

Given that we have a number of objective functions to choose from I think its worth some exploration of which one fits our needs best. 

What do you think?

Here what we have available to us:

![image](https://github.com/NCC-CNC/wheretowork/assets/3445092/a7281135-5e7a-41d0-9726-537630fb0e7a)

https://prioritizr.net/reference/objectives.html

**Comment by edwardsmarc** [comment]
A possible solution to this is to use `add_min_largest_shortfall_objective()` instead of `add_min_shortfall_objective()`. This will alter the behavior so instead of minimizing the total summed shortfall across all missed targets, it will instead try and make sure all missed targets are missed by the same amount. As stated in the prioritizr documentation: 

"In practice, this objective useful when the minimum shortfall objective returns solutions that focus too much on representing a small number of features (e.g., because they occur in much cheaper planning units), and solutions are needed to spread conservation effort out more evenly among all features—**even if it means that all features will have (relatively) poor representation**."

This could lead to fewer targets being met at a given budget, but solutions should be more nested. Here's an example using the BC data, note how different they are at lower area budgets. As budget increases they should converge towards the min set solution:
![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/07dce7de-c0e2-4bb9-8145-f8b5f69df78c)

Adding these solutions to ArcGIS confirms that the min_largest_shortfall solutions are almost completely nested. min_shortfall results become more nested as area budgets increase, but the lower area budgets have very poor nesting. 

**An important note is that with a 10% area budget min_largest_shortfall meets 69/919 targets, min_shortfall meets 599/919 targets.**

**Comment by edwardsmarc** [comment]
> Thanks very much for this @edwardsmarc!
> 
> I think the important note is very informative. What would be great additional information to have is what shortfall we have across the board for each of the objective functions. In your 10% area budget example, are many species getting close to meeting their target or do we see huge gaps? The jump from 69 to 599 is striking, but it would be interesting to learn whether its more nuanced than that.
> 
> Does that make sense?

Great idea Richard, I'll look into this today.

**Comment by edwardsmarc** [comment]
@ricschuster - I exported the Themes results into R and calculated target shortfall. The histograms of the shortfall are below. Shortfall was calculated as `(target area - solution area) / target area`.

The sum of the shortfall proportions were:
min_shortfall - 125.2
min_largest_shortfall - 450.0

The histograms make sense based on the objectives. min_shortfall has many more zero's (passed targets) and the non-passed targets follow a normal distribution. It's just trying to lower shortfall across all targets so it makes sense it has more passed targets. min_largest_shortfall has far fewer zeros, and it's distribution is capped at the max shortfall value. It's using PUs to lower the max shortfall value at the cost of passing targets because it doesn't care about the overall shortfall and there's no advantage for it to lower targets to zero.


![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/c7703bdf-6619-4476-aa17-38837ad68a48)
![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/99d4a68f-1036-493c-b2dd-0601eb3c80c2)

**Comment by ricschuster** [comment]
Thanks very much @edwardsmarc! That's super informative.

I am a bit surprised that min_shortfall is performing so much better than min_largest_shortfall when it comes to reaching targets across species and especially also much better at getting many species close to the target.

Given that the spatial configuration with min_shortfall changes so much in this example I am still thinking that there are just loads and loads of (almost) equally good solutions to the problem. Otherwise I could not really explain the substantial spatial shifts.

What are your thoughts on this? Are there other components we should explore still?

**Comment by edwardsmarc** [comment]
I ran some tests to better understand the objective functions and their behavior in WTW. I ran these on two example projects with quite high targets (requiring ~55-65% of PUs to meet all targets). I'm only showing the results from one example here (the BC pilot project with ~900 goals), the patterns hold in both examples.

I compared the following three objective functions, by increasing area budget through 10, 20, 30 and 40%:
- min shortfall - aims to minimize the overall shortfall across all goals. Doesn't care about meeting goals per se, meeting goals is a by-product of minimizing the shortfall.
- min largest shortfall - aims to minimize the maximum shortfall value across all goals. Doesn't care about meeting goals per se, meeting goals is a by-product of minimizing the shortfall.
- max features - aims to meet as many goals as possible. Doesn't care about shortfall. Returns the cheapest solution that meets the max number of features, meaning that solutions don't always use the full area budget.

No weights, includes or excludes were used. WTW was run locally using the gurobi optimizer.

Initial runs used the default 10% optimality gap, I then ran min_shortfall and max_features using 0% optimality gap to find the optimal solution for all scenarios. I also ran min_shortfall and max_features a second time at the 10% optimality gap to investigate variation between runs (these are labelled v1 and v2).



## Findings:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

objective | area_budget | targets_met | budget_used | max_shortfall | sum_shortfall
-- | -- | -- | -- | -- | --
BC_min_shortfall_v1 | 10 | 599/919 | 10% | 1 | 125.165929
BC_min_shortfall_v1 | 20 | 904/919 | 20% | 0.733822596 | 5.989286788
BC_min_shortfall_v1 | 30 | 909/919 | 30% | 0.667916283 | 2.750820035
BC_min_shortfall_v1 | 40 | 914/919 | 40% | 0.387030431 | 0.941938557
BC_min_shortfall_v2 | 10 | 599/919 | 10% | 1 | 125.165929
BC_min_shortfall_v2 | 20 | 905/919 | 20% | 0.733249913 | 5.989586416
BC_min_shortfall_v2 | 30 | 909/919 | 30% | 0.667916283 | 2.750820035
BC_min_shortfall_v2 | 40 | 914/919 | 40% | 0.387030431 | 0.941938557
BC_min_largest_shortfall | 10 | 69/919 | 10% | 0.725209912 | 450.0129896
BC_min_largest_shortfall | 20 | 430/919 | 20% | 0.501026288 | 168.4547934
BC_min_largest_shortfall | 30 | 655/919 | 30% | 0.310548827 | 56.37626388
BC_min_largest_shortfall | 40 | 756/919 | 40% | 0.145014397 | 15.63897465
BC_max_features_v1 | 10 | 670/919 | 10% | 0.968292738 | 132.8741275
BC_max_features_v1 | 20 | 903/919 | 20% | 0.733728478 | 6.227204128
BC_max_features_v1 | 30 | 894/919 | 23% | 0.7217185 | 6.220497752
BC_max_features_v1 | 40 | 896/919 | 38% | 0.437898271 | 2.444432356
BC_max_features_v2 | 10 | 591/919 | 10% | 1 | 124.171078
BC_max_features_v2 | 20 | 827/919 | 20% | 1 | 32.14001646
BC_max_features_v2 | 30 | 845/919 | 23% | 1 | 30.77135956
BC_max_features_v2 | 40 | 858/919 | 21% | 1 | 15.14245577

</body>

</html>

### min_largest_shortfall - low goals but nested
- Goals met are consistently far lower than the other two objectives
- The only positive is that this objective returns nicely nested solutions where the PUs for 10% are nested within 20% etc. This makes sense given that the objective is having to target every single Theme to collectively lower their shortfalls.

### min_shortfall vs. max_features
- Using the WTW 10% optimality gap, the min shortfall results make sense, total shortfalls decrease as area budgets increase. Goals met increase with area budget. The two runs return very similar results.
- The max_features results do not make sense. We would expect the number of goals passed to increase with area budget, and to always be higher that the min_shortfall results for a given area budget. Neither is always true. There is high variation between the two max_features runs.
- The results become clear when running at 0% optimality gap to find the best solutions for each run (see table below). Max_features are always higher than min_shortfall and goals passed increases with area budget in all cases. Max_features also appears to use most of the area budget when using 0% optimality gap, not the case at 10% optimality gap.
- Anecdotally, min_shortfall seems to run much faster than max_features.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

objective | area_budget | targets_met | budget_used | max_shortfall | sum_shortfall
-- | -- | -- | -- | -- | --
BC_min_shortfall_optimal | 10 | 633/919 | 10% | 0.999441091 | 122.8917863
BC_min_shortfall_optimal | 20 | 902/919 | 20% | 0.733428655 | 5.989221722
BC_min_shortfall_optimal | 30 | 907/919 | 30% | 0.668715845 | 2.750044396
BC_min_shortfall_optimal | 40 | 911/919 | 40% | 0.387292573 | 0.937594759
BC_max_features_optimal | 10 | 674/919 | 10% | 0.945102136 | 143.9265153
BC_max_features_optimal | 20 | 909/919 | 20% | 0.788131178 | 6.756184428
BC_max_features_optimal | 30 | 913/919 | 30% | 0.813227799 | 3.291804921
BC_max_features_optimal | 40 | 916/919 | 39% | 0.669025055 | 1.289055334

</body>

</html>


- Interestingly, I ran the min_set solution at 0% optimality gap and the % of planning units required to meet all targets decreased from 55% to 51%. This suggests that the max_features solutions needs to go from 20% to 51% of PUs just to meet the final 10 Theme goals. These tricky Themes are listed below:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MARC~1.EDW/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Theme | Feature | Total (units) | Goal (%) | Goal (units) | Solution (%) | Solution (units) | Met
-- | -- | -- | -- | -- | -- | -- | --
Connectivity (Mammal) | Caribou | 2327790.48 ha | 80 | 1862232.38 ha | 16.95 | 394548.98 ha | No
Connectivity (Mammal) | Fisher | 1094128.31 ha | 85 | 930009.06 ha | 31.73 | 347207.95 ha | No
Connectivity (Mammal) | Wolverine | 31817 ha | 65 | 20681.05 ha | 24.97 | 7946 ha | No
Connectivity (Habitat) | Grizzly Core | 1739540.49 ha | 70 | 1217678.34 ha | 22.13 | 384902.94 ha | No
Connectivity (Habitat) | Grizzly Linkage | 1204556.6 ha | 70 | 843189.62 ha | 21.66 | 260865.54 ha | No
Forest | Mature | 3711230.48 ha | 70 | 2597861.34 ha | 19.05 | 707142.28 ha | No
Forest | Old | 1242083.12 ha | 85 | 1055770.65 ha | 24.43 | 303484.75 ha | No
Pine | Limber (model) | 8339 km2 | 75 | 6254.25 km2 | 24.74 | 2063 km2 | No
Pine | Whitebark (model) | 23461 km2 | 75 | 17595.75 km2 | 21.37 | 5013 km2 | No
Water | Streams | 242129.5 ha | 45 | 108958.27 ha | 21.35 | 51701.55 ha | No

</body>

</html>


### min_shortfall and max_features are not nested at low area budgets
- This gets back to the original reason for this issue. The images below show the optimal solutions for min_shortfall and max_features at 10% and 20%. The issue here is that in both cases the 10% solutions are not nested very well within the 20% solutions. My explanation for this is included at the top of this issue. It's interesting that this behavior occurs with both objectives and in the optimal solutions which suggests it's not a function of the optimality gap.

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/e4f3a5ef-98b3-4820-9c35-f2cfdf0d9026)

### Conclusions
- max_features seems like the best option but it's slower and only makes sense at lower optimality gaps. So maybe sticking with min_shortfull is good enough. min_shortfall is more consistent between runs which is a user concern, and it does pretty good on meeting goals, just not as good as max_features.
- I don't have any conclusions on the spatial nesting. min_largest_shortfall is a non-starter in terms of meeting goals, and while this test has shown the observed non-nesting behavior in min_shortfall and max_features is genuine (not a bug), it's going to be hard to explain this to users who expect solutions to be nested.

I'm wondering if @jeffreyhanson can provide any comments here, two Q's for him:
1. Have you come across this non-nested patterning before in cases where the available budget is well below what is needed to meet all targets?
2. Do you have any thoughts on the objective functions? Is it possible to have a function combining max_features and min_shortfall where it first tries to meet as many targets as possible, then tries to minimise shortfall with the left over budget?

**Comment by ricschuster** [comment]
Thanks very much @edwardsmarc! This is really great information. When you mention `max_features` being slower do you have some timing numbers for reference? I'd be curious to know how much of a difference we are expecting for this.

**Comment by edwardsmarc** [comment]
> Thanks very much @edwardsmarc! This is really great information. When you mention `max_features` being slower do you have some timing numbers for reference? I'd be curious to know how much of a difference we are expecting for this.

Thanks @ricschuster, I'll run some benchmarks next week to get timings.

**Comment by edwardsmarc** [comment]
@ricschuster here are some benchmarks in minutes for various objective functions and area budgets. I ran each scenario twice. This is using gurobi and prioritizr in Rstudio. The obvious outlier is max_features at 10% area budget, I'm not sure why this one takes so much longer.

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/428fba6a-6228-43b5-9936-a15456e5121c)

**Comment by jeffreyhanson** [comment]
Hi,

Sorry for my slow response, I'm travelling at the moment.

> 1. Have you come across this non-nested patterning before in cases where the available budget is well below what is needed to meet all targets?

Yeah, the non-nested patterning is very common, and I would argue is a feature not a bug. We get the non-nestedness because the prioritization is not generated using ranking algorithms (c.f. Zonation) and is instead generated using algorithms that provide optimality gurantees. For example, consider the following scenario: we have 1 feature and 4 planning units. The amount of the feature within each of the planning units is {0.01, 0.02, 0.03, 0.9} and the costs of the planning unit is {1, 2, 3, 100}. Let's also assume we have a min-shortfall objective with a target of 100%. If we have a budget of 6, then we can only get the first three planing units, giving us a total for feature 1 of `0.01 + 0.02 + 0.03 =0.06`. However, if we increase the budget to 100, then we would just select the fourth planning unit, and giving us a total amount of `0.9`. As we can see, we when we increase the available budget, this can totally alter the solution, such that we might get a solution that contains none of the planning units selected at a smaller budget. This is an extreme example designed to illustrate a point. In most cases, we don't see such a drastic change, but we do find that some planning units selected under smaller budgets are not selected at higher budgets. If you forced the solutions to exhibit nesting (e.g., by using ranking algorithms), then this can drastically reduce the performance of the solutlon at a particular budget.

If you think the nestedness is important, one way to ensure that a solution based on a higher budget is an expanded version of a solution based on a lower budget (i.e. ensure the nestedness) is to use the locked in constraints so that all planning units in the first cheaper solution are locked in when generating the second solution. This approach is used to help schedule planning decisions (e,..g, what to buy in time step 1, then in time step 2, then in time step 3, etc) or identify sets of priority areas of decreasing importance (e.g., see https://doi.org/10.1038/s41559-021-01528-7). Note that this method will still degrade performance.

> 2. Do you have any thoughts on the objective functions? Is it possible to have a function combining max_features and min_shortfall where it first tries to meet as many targets as possible, then tries to minimise shortfall with the left over budget?

I would personally just stick with the min shortfall because it's relatively simple to explain, quick to run, and does a good job at ensuring that the solution doesn't neglect too many features. One big limitation of the max features objective is that is treats targets as an "all or nothing" -- meaning that when budgets are small it tends to produce solutions that are very biased towards representing a few features and does a really bad job at representing all the other features in the prioritization. Although you could do a two-step prioritization that generated a solution based on the max features objective and then allocates the remaining budget to reduce shortfalls (i.e., using linear constraints to ensure that the features that are adequtely represented by the first prioritization will still have their targets met by the second prioritization), this would probably increase run time by a fair bit and would still likely have the bias issues.

How does that sound?

**Comment by edwardsmarc** [comment]
Thanks @jeffreyhanson, this is a great explanation and pretty much confirms the conclusions we were leaning towards.

That Nature paper is great! I think that could provide a good reference to our users and I like the idea of locking in the lower area budget solutions if nestedness is important. I'm starting to realize that as users get more comfortable and advanced they'll be able to make these decisions themselves, so a big role for us is to just communicate the underlying methods so they understand what the tool is doing.

I agree sticking with min_shortfall seems like the best option.

I've added an issue for a vignette to explain the objective functions. I don't expect all new users will want to read this, but more advanced users will, and it'll give us something to reference when users get confused about the 'best' PUs not appearing in all area-budget solutions.

**Comment by edwardsmarc** [comment]
Closing this following updates to the website with vignettes explaining the above discussion points (https://github.com/NCC-CNC/wheretowork/pull/334).

We'll stick with min_shortfall, the behaviour described in this issue is now explained in https://ncc-cnc.github.io/wheretowork/articles/articles/wtw_theory.html
