### ISSUE TITLE
Vignette - wtw theory

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#326]
Following the discussion in #321, We need something that users can refer to to understand the objective functions (and to a lesser degree the weights), and how they could adapt their use of the tool based on their planning scenario and expectations (e.g. nestedness).

No area-budget
- min_set_objective, always meets all targets using the cheapest solution

Area budget
- min_shortfall_objective, does a good job of minimizing the missing targets while representing most species
- Briefly explain that solutions are not nested, see #321
- Users can use `includes` if they want the 'best' areas to appear in all solutions. For example, they could lock in the areas of especially high quality habitat for important species if they want those areas to be the starting point for all solutions. Or they could lock-in the solutions from lower area-budgets when running higher area-budgets. Both of these approaches would reduce the behavior described in #321 where lower area-budget solutions are not nested within higher area-budget solutions.

Weights
- When no area budget, weights change the `cost` of planning units such that planning units with higher weights will have lower costs and will therefore be preferred in solutions.
- When area budget is used, weights become additional targets such that the solution will attempt to include all weights in the solution (but see #323 for exact behavior).

Also describe optimality gap and it's impact on results
- run some tests to see how much min_set and min_shortfall are impacted by 10% optimality gap.

**Comment by ricschuster** [comment]
I haven't head a chance to read #321 in full yet, but this is a great idea!
This will really help Where To Work users.

**Comment by edwardsmarc** [comment]
closed with https://github.com/NCC-CNC/wheretowork/pull/334
