### ISSUE TITLE
continuous raster display has "holes"

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#330]
I mostly notice this when vector species habitat data has been prepped as continuous. The "edges" show a gradient where the "core" displays these "holes".

![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/d1d3306e-3c4e-410e-b3a5-fb4e90c0d857)

**Comment by DanWismer** [comment]
A more obvious example:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/fea59090-8174-424c-8d83-8273e26327b3)

**Comment by edwardsmarc** [comment]
Weird, are the input tifs normal or do they also have holes?

**Comment by DanWismer** [comment]
The input tifs don't have those holes. The screen shots above are from the updated ECCC CH / ECCC SAR layers I converted to continuous. I noticed this behavior on the regional WTW projects. The same thing is happening in the `Aspen Parkland, Boreal Fringe` built-in project (Key Range Layers).

Rasters are projected on the fly to web Mercator, using the bilinear method for continuous data. I am wondering if something is happening there. Perhaps something to do if continuous layers have a low unique value count?

**Comment by DanWismer** [comment]
For continuous rasters "bilinear" is used for resample: https://github.com/NCC-CNC/wheretowork/blob/516af492d051f2e8e2ea95185fea76fd912fc505/R/class_ContinuousLegend.R#L69

I switched it to "ngb" and I get no holes:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/8d0be662-f51a-4d65-a480-8dcf0670da4e)

I am wondering if there is a threshold between the number of unique values and interpolation method?

An aside, I am liking having the continuous layers only display where there are values >0.
