### ISSUE TITLE
Logos for website

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#336]
Great work on the website @edwardsmarc!

I really like this!

One quick comment:
We should create something similar to the WTW landing page here to acknowledge develpers and funders:

![image](https://github.com/NCC-CNC/wheretowork/assets/3445092/62d90b2f-a2c7-4859-a499-c7829c54a049)

**Comment by DanWismer** [comment]
@edwardsmarc this is a huge improvement. Its great that we can now point users to those articles.

In terms of the logos, the raw files are here:
https://github.com/NCC-CNC/web-apps-logos

**Comment by edwardsmarc** [comment]
Thanks @DanWismer. For now I've just dropped in the png that Richard copied above. When the app goes public we might want to spruce up the website again. That would include adding hyperlinks to all those logos.

In a past project I made a nice website using RMarkdown and html (not pkgdown). It looks more professional but took considerably more time: https://casfri.github.io/CASFRI/

**Comment by DanWismer** [comment]
unfortunately, there is now an issue reported by Eleanor that wheretowork will not install. 

```
* preparing 'wheretowork':
* checking DESCRIPTION meta-information ... ERROR
Authors@R field gives more than one person with maintainer role:
  Jeffrey O Hanson <jeffrey.hanson@uqconnect.edu.au> [aut, cre] (<[https://orcid.org/0000-0002-4716-6134>)](https://orcid.org/0000-0002-4716-6134%3E))
  Dan Wismer <dan.wismer@natureconservancy.ca> [cre]
  Marc Edwards <marc.edwards@natureconservancy.ca> [cre]

 

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
STDOUT:
* checking for file 'C:\Users\Eleanor Gallant\AppData\Local\Temp\RtmpayhBts\remotes7384205b7bf\NCC-CNC-wheretowork-311dfd2/DESCRIPTION' ... OK
* preparing 'wheretowork':
* checking DESCRIPTION meta-information ... ERROR
Authors@R field gives more than one person with maintainer role:
  Jeffrey O Hanson <jeffrey.hanson@uqconnect.edu.au> [aut, cre] (<[https://orcid.org/0000-0002-4716-6134>)](https://orcid.org/0000-0002-4716-6134%3E))
  Dan Wismer <dan.wismer@natureconservancy.ca> [cre]
  Marc Edwards <marc.edwards@natureconservancy.ca> [cre]

 

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
STDERR:

 

Error: Failed to install 'wheretowork' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘wheretowork’
2: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘prioritizr’ had non-zero exit status
  ```

**Comment by edwardsmarc** [comment]
Yeah I just got that too. I'm fixing it in my current branch. If she needs a quick local fix, just send her your DESCRIPTION file, or she can delete our names from the DESCRIPTION file.

**Comment by DanWismer** [comment]
Thanks @edwardsmarc

**Comment by edwardsmarc** [comment]
Closing as the original issue has been resolved and the DESCRIPTION has been fixed on main.
