### ISSUE TITLE
Remove scales::rescale() when upgrading to prioritizr v8

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#341]
scales::rescale() causes problems with boundary data when used in the newest prioritizr version: https://github.com/prioritizr/prioritizr/issues/297

Currently we are using an older version of prioritizr but when we update the packages (https://github.com/NCC-CNC/wheretowork/issues/303#issuecomment-1494585277_) we'll need to make sure we apply the change recommended by @jeffreyhanson in the prioritizr issue.

Only effects the use of scales::rescale() in fct_min_set_result() and fct_min_shortfall_result() when prepping the boundary matrix.

**Comment by DanWismer** [comment]
PR #380
