### ISSUE TITLE
Flip Theme tabs to "single" then "group"

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#344]
Following up in the wtw-data-prep issue about goal setting: https://github.com/NCC-CNC/wtw-data-prep/issues/23

The Rodrigues goals is causing the group goals to be 100% for most cases. And having group goals at 100% is causing the output to select the entire AOI.
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/6451a977-190c-4585-9000-1a6eed6057fd)

We should have the single tab ordered first and activated when the app launches:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/eed53848-685c-44a5-bc06-df9897a4aae7)

Also, we should think about not dynamically having the grouped goals set, but rather have them all set to 0 (or maybe 0.2). That way the user has to explicitly set the group goal.

**Comment by DanWismer** [comment]
I am thinking that maybe this can be handled in data prep. We keep group goals at a default 20% and also keep the single group goals

**Comment by DanWismer** [comment]
I can hard code this variable to `0.2`, which will initialize all group goals to 20%.

https://github.com/NCC-CNC/wheretowork/blob/af2a90b967b5b87736635393658b3d894465f3ac/inst/htmlwidgets/lib/solutionSettings-1.0.0/MultiThemeSetting-class.js#L32

@ricschuster @edwardsmarc @jeffreyhanson 
This is the easiest solution. Are we ok with hard coding group goals when the app spins ups? For now this makes sense to me in the short term. In the long term, we could add another theme attribute specifically for group goals on initialization, however I would need to touch a lot of the code base + data prep scripts to make that work. 

Another question for everyone - should the tab be on `single` or `group` when the app spins up? In order for our national goals to work, the multi-theme tab needs to be on `single`. 

Another idea I have is a button that can switch all the multi-theme tabs to either `single` or `group` in one shot, instead of scrolling down and doing it manually for each multi-theme.

**Comment by edwardsmarc** [comment]
Hey Dan, I think it should be set to 'single' when the app spins up. That way ppl can see all the default goals. I like the idea that if someone just spins it up and hits go, it'll have our preferred CP&P default parameters set.

And yes, the group goal has to default to something and 20% is as good as any other value imo.

I do like your last idea of having an option to flip all themes between group and single with one click.

**Comment by ricschuster** [comment]
Thanks very much Dan!

I agree with everything Marc responded with. 
The default behavior should replicate CP&P default parameters.

**Comment by DanWismer** [comment]
Thanks @edwardsmarc and @ricschuster! I will set is so the single tab is enabled and hard code group goals to 20% when the app spins up.
