### ISSUE TITLE
Species typo in built in project

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#357]
Built in project for Aspen Parkland has a typo where "Piping Plover" is listed as "Piping Plower".

![image](https://github.com/NCC-CNC/wheretowork/assets/10728298/bb276494-a226-4012-b348-910eec6a2e61)

**Comment by DanWismer** [comment]
The Key Wildlife Layer (AEP) is regional data. That typo needs to be updated on the data prep that AB did.
