### ISSUE TITLE
fix notes on R CMD Check

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#362]
two notes I think can be fixed:

- "checking top-level files" `index.Rmd and `index.md`.  https://github.com/r-lib/pkgdown/issues/709

- 
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/b2611e58-c1e4-4395-9f63-1a26dd4e5561)

**Comment by DanWismer** [comment]
@edwardsmarc this is one of the notes:
![image](https://github.com/user-attachments/assets/ba04fbbd-1b1a-4df4-935a-6ae7d69a32e3)

I believe this is from the pkgdown site you created: https://ncc-cnc.github.io/wheretowork/

I think I can move them into that pkgdown folder and recreate the site?

**Comment by edwardsmarc** [comment]
Yes, I think that should work based on this description:

https://pkgdown.r-lib.org/reference/build_home.html

**Comment by DanWismer** [comment]
PR #380
