### ISSUE TITLE
expired envvar GITHUB_PAT?

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#366]
Was doing some wtw prep and need to install WTW as a package:

When I run `remotes::install_github("NCC-CNC/wheretowork")` I get an error:

```
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo NCC-CNC/wheretowork@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
 download from 'https://api.github.com/repos/NCC-CNC/wheretowork/tarball/HEAD' failed
```
  
  @jeffreyhanson I am wondering if a PAT is expired? Would it be my own, or one we have set in this repo?

**Comment by DanWismer** [comment]
weird, I was able to get it to start installing by doing this: `options(download.file.method = "wininet")`

https://github.com/forestgeo/learn/issues/102

**Comment by jeffreyhanson** [comment]
Hmm, that's strange. No idea why that's happening sorry. Maybe GitHub recently updated something, and now the developers of remotes need to update something to maintain compatibility?

**Comment by DanWismer** [comment]
Strange indeed. For now the `options(download.file.method = "wininet")` works, so I will close this.
