### ISSUE TITLE
rgdal has been removed from CRAN

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#367]
Can't install wheretowork because of this. We should remove rgdal.

**Comment by DanWismer** [comment]
@jeffreyhanson I only see a single call to rgdal here:
https://github.com/NCC-CNC/wheretowork/blob/45f2a652e6a4cfe89e4a521d9b944c003d66086d/R/package.R#L46

Can you bring me up to speed on this tmp1 variable? I don't see any calls to it.

**Comment by jeffreyhanson** [comment]
Yeah, if I remember correctly, older versions of the raster package needed to have the rgdal pacakge installed (as an optional depedency) to import geotiff files. My understanding is that has now changed with more recent versions of the raster package. So, if you update the version of the raster package in the renv environment, you should then be able to remove rgdal without loss of functionality.

**Comment by DanWismer** [comment]
Thanks Jeff! Your right, as of version [3.6-3](https://cran.r-project.org/web/packages/raster/NEWS) rgdal is no longer used.

I updated to the latest raster package and removed rgdal from WTW

**Comment by DanWismer** [comment]
@ricschuster @edwardsmarc, I have pushed these changes to dev, and they are live on the CAR-DEV server. When you have time, could you do a quick run?  Monday I will merge this into main.

**Comment by jeffreyhanson** [comment]
Awsesome - thanks @DanWismer!

**Comment by edwardsmarc** [comment]
@DanWismer the dev site works fine for me.

**Comment by ricschuster** [comment]
@DanWismer works for me too.
