### ISSUE TITLE
update to latest prioritizr version

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#369]
@jeffreyhanson do you know any gotchyeas I should be aware of? I believe I will need to update everything to use terra first.

**Comment by jeffreyhanson** [comment]
Hmm, possibly you might need to use `rescale_matrix()` when re-scaling the boundary data (assuming code currently uses `scales::rescale()`)? Other than that I don't think so. Just to be safe, could you take a look at the [NEWS file](https://github.com/prioritizr/prioritizr/blob/main/NEWS.md) and see if there's any "Major changes" or "Notice" sections that appear after the version of prioritizr that WTW's currently using?

**Comment by DanWismer** [comment]
@jeffreyhanson any idea on what I should look into for this:
![image](https://github.com/user-attachments/assets/f1e45353-a1c6-4b36-800c-5df2e39b9524)

**Comment by DanWismer** [comment]
oh maybe this:
https://github.com/prioritizr/prioritizr/issues/283

So we should use `base::solve` ?

**Comment by DanWismer** [comment]
ok it worked! And I have an output. But now this:
![image](https://github.com/user-attachments/assets/882bac20-c670-4255-8014-9f57f232e737)

**Comment by DanWismer** [comment]
I see in the NEWS that on prioritizr version 8.0.2.7, `scales::rescale` is no good any more. You say to change it to `rescale_matrix`. I will change all the calls the scales and see if that helps

**Comment by DanWismer** [comment]
In updated version 8.0.2, I see this:
![image](https://github.com/user-attachments/assets/ced78b52-e033-4cad-9048-d87b7d6479bf)

@jeffreyhanson 
Does this mean that all previous prepped boundary.csv.gz files wont ingest?

**Comment by DanWismer** [comment]
I ran spatial cluster scenario with the SW Ontario example data and got this:
![image](https://github.com/user-attachments/assets/b380e79d-89ab-44e3-a48a-279324fb05eb)

**Comment by jeffreyhanson** [comment]
Yeah, that's right. You'll need to remake all the boundary.csv.gz files so that they follow the new format. It might be possible to create some function to convert/update the files - not sure though.

**Comment by DanWismer** [comment]
@jeffreyhanson, can you bring me up to speed on these warnings?
![image](https://github.com/user-attachments/assets/8ba34106-ea46-4a8f-923c-f36e6a39dd42)

**Comment by DanWismer** [comment]
also @jeffreyhanson , how do I address this?
![image](https://github.com/user-attachments/assets/a4da7cf0-7802-4df7-9727-0b456c65c780)

Never got this error previously - but I have updated a lot of things since then

**Comment by DanWismer** [comment]
@jeffreyhanson I am getting an error here when running the tests:
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L287

![image](https://github.com/user-attachments/assets/6be05181-0283-4891-931d-0d901ed211c6)

**Comment by jeffreyhanson** [comment]
> @jeffreyhanson, can you bring me up to speed on these warnings? ![image](https://private-user-images.githubusercontent.com/29556279/360537863-8ba34106-ea46-4a8f-923c-f36e6a39dd42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTY1ODUsIm5iZiI6MTcyNDM1NjI4NSwicGF0aCI6Ii8yOTU1NjI3OS8zNjA1Mzc4NjMtOGJhMzQxMDYtZWE0Ni00YThmLTkyM2MtZjM2ZTZhMzlkZDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE5NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMDIzYmQyZDVjOWI1MjNmYWU5MWU2Zjc1ZjhmNWQzODBmZGI5ZDBmYjgxOTUxZjEzYzNkOTNjOTE2Zjc4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGO2l1CP4zaThQLBQ-BUDmM8egUXTDOMdEJPmfWO9XY)

This warning is saying that you have spatial polygon/vector data for the planning units, and some of the planning units might be overlapping with each other. This could be a problem because planning units should generally correspond to different areas.

**Comment by jeffreyhanson** [comment]
> @jeffreyhanson I am getting an error here when running the tests:
> 
> https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L287
> 
> ![image](https://private-user-images.githubusercontent.com/29556279/360556033-6be05181-0283-4891-931d-0d901ed211c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTY4NjgsIm5iZiI6MTcyNDM1NjU2OCwicGF0aCI6Ii8yOTU1NjI3OS8zNjA1NTYwMzMtNmJlMDUxODEtMDI4My00ODkxLTkzMWQtMGQ5MDFlZDIxMWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE5NTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTA3MWRiODc0NGFkYWY0ZGFhYTI0ZDQ0ZDgxZWY0OWMwNzMzMTBhMjIxOGNkN2ZjZmYwZWNjM2YzYjQ2YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-EZ0Xh_2OCim9Tr6KKa-YrePCBbr6_p4r5wOpZMgWnE)
> 
> I see that `locked_in * include_data` is not an array. And ` include_data` is not an array. Wonder if something changed in the updated Matrix package?
> 
> ... I don't think this is related but I am seeing that `dsTMatrix` is deprecated and to use `TsparseMatrix` instead
> 
> What kind of object is `locked_in * include_data`? E.g., what if you do `class(locked_in * include_data)`? My initial guess is that it is a Matrix-class object from the Matrix package, so maybe try `Matrix::colSums(locked_in * include_data)`?

What kind of object is `locked_in * include_data`? E.g., what if you do `class(locked_in * include_data)`? My initial guess is that it is a Matrix-class object from the Matrix package, so maybe try `Matrix::colSums(locked_in * include_data)`?

**Comment by DanWismer** [comment]
> > @jeffreyhanson I am getting an error here when running the tests:
> > https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L287
> > 
> > ![image](https://private-user-images.githubusercontent.com/29556279/360556033-6be05181-0283-4891-931d-0d901ed211c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTY4NjgsIm5iZiI6MTcyNDM1NjU2OCwicGF0aCI6Ii8yOTU1NjI3OS8zNjA1NTYwMzMtNmJlMDUxODEtMDI4My00ODkxLTkzMWQtMGQ5MDFlZDIxMWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE5NTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTA3MWRiODc0NGFkYWY0ZGFhYTI0ZDQ0ZDgxZWY0OWMwNzMzMTBhMjIxOGNkN2ZjZmYwZWNjM2YzYjQ2YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-EZ0Xh_2OCim9Tr6KKa-YrePCBbr6_p4r5wOpZMgWnE)
> > I see that `locked_in * include_data` is not an array. And ` include_data` is not an array. Wonder if something changed in the updated Matrix package?
> > ... I don't think this is related but I am seeing that `dsTMatrix` is deprecated and to use `TsparseMatrix` instead
> > What kind of object is `locked_in * include_data`? E.g., what if you do `class(locked_in * include_data)`? My initial guess is that it is a Matrix-class object from the Matrix package, so maybe try `Matrix::colSums(locked_in * include_data)`?
> 
> What kind of object is `locked_in * include_data`? E.g., what if you do `class(locked_in * include_data)`? My initial guess is that it is a Matrix-class object from the Matrix package, so maybe try `Matrix::colSums(locked_in * include_data)`?
> 
> Sorry, I accidently edited your previous comment - I accidently clicked the wrong button, I meant to click quote reply instead.

Thanks Jeff, adding `Matrix::` does the trick, it works now. Curious why this wouldn't error before...

**Comment by DanWismer** [comment]
@jeffreyhanson, do you think this function can be replaced with something in the prioritizr 8.04 version?
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L485-L487

I see we have it here,
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/internal.R#L235

**Comment by jeffreyhanson** [comment]
My guess would be that this is either (1) due to an update in the Matrix package or (2) an update to how prioritizr imports the Matrix package (e.g., maybe prioritizr had Matrix package listed as Depends in the older version).

> @jeffreyhanson, do you think this function can be replaced with something in the prioritizr 8.04 version?
> 
> https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L485-L487
> 
> I see we have it here,
> 
> https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/internal.R#L235

My guess would be that this is either (1) due to an update in the Matrix package or (2) an update to how prioritizr imports the Matrix package (e.g., maybe prioritizr had Matrix package listed as Depends in the older version).

**Comment by jeffreyhanson** [comment]
> @jeffreyhanson, do you think this function can be replaced with something in the prioritizr 8.04 version?
> 
> https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L485-L487
> 
> I see we have it here,
> 
> https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/internal.R#L235

Hmm, maybe - but I wouldn't recommend relying on internal functions in R packages. In general, I'd recommend either using the exported functions or duplicating the internal functions as needed to avoid issues with future compatibility. For WTW, I copied the internal function to aovid overheads associated with the exported function.

**Comment by DanWismer** [comment]
@jeffreyhanson any thoughts on this one? I get it when testing the `min_set_result` spatial clustering
![image](https://github.com/user-attachments/assets/e5a17555-c63d-425c-98d3-91f1331eb2ba)

**Comment by jeffreyhanson** [comment]
> @jeffreyhanson any thoughts on this one? I get it when testing the `min_set_result` spatial clustering ![image](https://private-user-images.githubusercontent.com/29556279/360669479-e5a17555-c63d-425c-98d3-91f1331eb2ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjIwNzUsIm5iZiI6MTcyNDM2MTc3NSwicGF0aCI6Ii8yOTU1NjI3OS8zNjA2Njk0NzktZTVhMTc1NTUtYzYzZC00MjVjLTk4ZDMtOTFmMTMzMWViMmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIxMjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1M2Y1ODBkMWZlYWQ2N2E2ZGM5YWVjZjlmZDUyMjczMTZlNDY5NGJmMjY1NWYwYzI4N2Y4ZDliOGQ4NDhhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Ezq0Y92qO4ep35U-lCzMug3MnIkw8QW4o2_JoTgyRg)

Hmm, how is `con_data` being calculated?

**Comment by DanWismer** [comment]
> > @jeffreyhanson any thoughts on this one? I get it when testing the `min_set_result` spatial clustering ![image](https://private-user-images.githubusercontent.com/29556279/360669479-e5a17555-c63d-425c-98d3-91f1331eb2ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjIwNzUsIm5iZiI6MTcyNDM2MTc3NSwicGF0aCI6Ii8yOTU1NjI3OS8zNjA2Njk0NzktZTVhMTc1NTUtYzYzZC00MjVjLTk4ZDMtOTFmMTMzMWViMmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIxMjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1M2Y1ODBkMWZlYWQ2N2E2ZGM5YWVjZjlmZDUyMjczMTZlNDY5NGJmMjY1NWYwYzI4N2Y4ZDliOGQ4NDhhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Ezq0Y92qO4ep35U-lCzMug3MnIkw8QW4o2_JoTgyRg)
> 
> Hmm, how is `con_data` being calculated?

its from here:
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L488-L495

Do I need to change anything with generating the bm?
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/class_Dataset.R#L672-L679

**Comment by jeffreyhanson** [comment]
Hmm, just quickly looking at the code, i would have expected this to provide a symmetric connectivity matrix. So, I wouldn't ignore the warning. I'd suggest digging into and seeing if you can work out why the connectivity data are asymmetric.

**Comment by DanWismer** [comment]
> Hmm, just quickly looking at the code, i would have expected this to provide a symmetric connectivity matrix. So, I wouldn't ignore the warning. I'd suggest digging into it and seeing if you can work out why the connectivity data are asymmetric (or why prioritizr thinks the data are asymmetric). One guess is that the `rescale()` bit might be to blame here.

Thanks Jeff, I will take a deeper dive and let you know what I find.

**Comment by DanWismer** [comment]
I am wondering if this can all be replaced.
https://github.com/NCC-CNC/wheretowork/blob/master/R/fct_simulate_spatial_data.R

And use your simulation functions in prioritizr? 
https://prioritizr.net/reference/simulate_data.html

**Comment by DanWismer** [comment]
Ok, all tests are passing except `test_min_set_result` - spatial clustering.
![image](https://github.com/user-attachments/assets/1feaa3fe-7f7a-47c4-ae78-c56a2ef33814)

**Comment by jeffreyhanson** [comment]
Yeah, replacing `scales::rescale()` with `rescale_matrix()`  is a great idea! I would have hoped that would have fixed it.  Sorry to hear it's still not working.

Would it be possible to put togeather a small example dataset (e.g. 5 planning units, 4 features), so we can step through chunk of code in an interactive session and see what the `con_data` matrix looks like? It might be poissible to create this small example dataset with the simulation functions? How does that sound?

**Comment by DanWismer** [comment]
Flagging this here:
![image](https://github.com/user-attachments/assets/5b874b97-0088-41f1-8323-1d38f1375676)

New Matrix package stuff

**Comment by jeffreyhanson** [comment]
Yeah, hopefully this shouldn't be too tricky to fix. It hopefully be as simple as replacing `as(x, "dgTMatrix")` with `as(as(x, "generalMatrix"), "TsparseMatrix")` like it says - but let me know if you run into any issues? I've had deal similar matrix conversion issues in prioritizr.

**Comment by DanWismer** [comment]
@jeffreyhanson thanks for your help with the boundary stuff! 

Reviewing the `fct_min_set_result`, I see there are more instances of `scales::rescale`
Should I be changing all these to `prioritizr::rescale_matrix` ?

For example:
https://github.com/NCC-CNC/wheretowork/blob/316b2567ecc5a7d35572994490c34ec40d2403df/R/fct_min_set_result.R#L327-L351

**Comment by edwardsmarc** [comment]
Those calls are rescaling vectors of numbers, not matrices, so I think they are OK. But I'll let @jeffreyhanson confirm!

**Comment by jeffreyhanson** [comment]
No worries @DanWismer - happy to help! Yeah, that's right @edwardsmarc. The `scales::recale()` is being used correctly here to rescale numeric vectors. The `prioritizr::rescale_matrix()` function should only be used on boundary or connectivity matrices.

**Comment by DanWismer** [comment]
Thanks guys!!

**Comment by DanWismer** [comment]
PR #380
