### ISSUE TITLE
Q. MASS package 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#375]
@jeffreyhanson do you recall why we need the MASS package?

I am attempting to update library's as I work through updating terra. Getting into a bit of a spider web with renv. 

https://forum.posit.co/t/mass-not-available-for-r-4-3-3/188156

**Comment by DanWismer** [comment]
ok, I think these are packages that come with an installation of R:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/7e97b6a3-57b1-48f5-bfd7-b8177a452714)

**Comment by jeffreyhanson** [comment]
Hi,

Sorry, I don't know/remember. Although I don't think we use it directly in WTW, I think it might be a dependency. You can see which packages use MASS by looking at "Reverse Depends" and "Reverse Imports" on its CRAN web page (https://cran.r-project.org/web/packages/MASS/index.html). So it might be possible to cross-reference the packages listed there with the packages in the `renv.lock` file to narrow down why we/if need MASS?

**Comment by jeffreyhanson** [comment]
Oh I see

**Comment by DanWismer** [comment]
I think its the Matrix package that needs it, which is also a base package with R

**Comment by DanWismer** [comment]
However it is only under suggests https://cran.r-project.org/web/packages/Matrix/index.html

**Comment by DanWismer** [comment]
with these base packages, is it even possible to go to an older version?

for example. I am seeing if I can update WTW to run on the latest version of R (4.4.1). When doing renv:restore, MASS package wont install because the renv.lock is wanting to use MASS 7.3-54, which I assume is a version that shipped with R 4.1.2 (this is the R version WTW currently runs on). 

I am wondering why it is not just grabbing the older achieved one

**Comment by jeffreyhanson** [comment]
I don't think so. AFAIK the base packages are tied pretty to R's internals. So, it might not be possible to use a different version of R's base packages with a different version of R. But I might be wrong? I haven't tried actually doing this.

**Comment by DanWismer** [comment]
Maybe? I haven't read this yet:
https://stackoverflow.com/questions/76469848/compilation-error-building-archive-version-of-mass-on-macos

**Comment by DanWismer** [comment]
I guess if these are base packages, does renv really need to be tracking them? My guess is that base packages only run on the R version they come up?

**Comment by jeffreyhanson** [comment]
Well, if you want to ensure that R code that runs on machine A also works on machine B, and you're using functions in the base packages (e.g., the new `|>` operator), then it would be important to be track them? I guess it depends on "reproducible"/"replicable" things need to be.

**Comment by jeffreyhanson** [comment]
Maybe the latest version of terra (or one of it's dependencies) only works on a more recent version of R than what is currently being used, and that's what's causing this issue?

**Comment by DanWismer** [comment]
With all this, my understanding is that it is best to pick one version of R that you want renv to be compatible with. And only support that. In other words, you can not support multiple R versions at the same time with renv.  

Its upgrade R version. And bring everything along with it. Then once updated to say R 4.4. The WTW will no longer be compatible with R 4.1.2

Does that make sense?

**Comment by jeffreyhanson** [comment]
Hmm, thinking more about this and doing some more reading, I don't think renv has to neccesarily work with a particular version of R (though this can be done by specifying this info in the renv lock file). I think the issue is that MASS is a recommended package (not a base package, see https://stackoverflow.com/a/9705725) so it is automatically installed along with R by default. I also see that renv for WTW is congfigured to only work with R version 4.1.2 (https://github.com/NCC-CNC/wheretowork/blob/master/renv.lock#L2-L10) so perhaps this why it's not working? Maybe the version of MASS you're trying to install isn't compatible with R 4.1.2?

**Comment by jeffreyhanson** [comment]
If you're trying to install the latest version of MASS, we can indeed see that it needs R version 4.4.0 (see "Depends" entry in https://cran.r-project.org/web/packages/MASS/index.html) -- so I think this is what is happening here. I also see something similar for the latest version of the Matrix too (https://cran.r-project.org/web/packages/Matrix/index.html).

**Comment by jeffreyhanson** [comment]
Note that the in renv, the configuration for specifying a particular version of R is optional. So e.g., you could remove this part of the lock file so that it could potentially work on any version of R (assuming that the packages listed in the lock file are compatible with a given R version)
