### ISSUE TITLE
Where To Work Title

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#379]
Any intrest in dropping the WTW title on the map?

![image](https://github.com/user-attachments/assets/94788365-904c-45af-8dff-d7da1bb50b50)

Also changing the import modal to this:
![image](https://github.com/user-attachments/assets/a461f797-1f63-4814-856f-a9451d85fd1b)

**Comment by ricschuster** [comment]
Come branding on the map would be good, but does not need to be title I would say.

For the import modal, is the difference the version number?

**Comment by DanWismer** [comment]
We don't specify the version number which would be `0.0.9000`. Once I merge in all the updates I have been working on, we will do an official version bump to `1.0.0`.

Sounds good, I will keep the map title. Can't think of an easy location to put the branding on the map

**Comment by ricschuster** [comment]
Sounds good about the modal.

As for map title, we could make it smaller.

**Comment by DanWismer** [comment]
PR #380
