### ISSUE TITLE
Ability to upload settings

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#90]
It would be great if users could upload a spreadsheet containing settings (e.g. parameters, theme goals, weight factors, etc) so that could generate solutions without needing to play around with the sliders/buttons.

**Comment by DanWismer** [comment]
Didn't see this, I opened a new issue on this, but more for the download aspect of settings issue #274

**Comment by DanWismer** [comment]
PR #285
