### ISSUE TITLE
NCC acknowledgement text

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#92]
The text acknowledging NCC for the development of the app needs to be finalized. @ricschuster, IIRC you mentioned that MM was working on drafting some text to include in the app - is that right? If so, did she send you the text for the app?

**Comment by jeffreyhanson** [comment]
@ricschuster, I just wanted to follow up and ask about the acknowedgement text? At the moment, the app contains the following place-holder text "The Where To Work application is proudly developed by the Nature Conservancy of Canada". If you're happy with that then we can close the issue?

**Comment by ricschuster** [comment]
We should check with Joe about how he wants Carleton to be acknowledged.
Also, the main credit should go to you. How would you like to be acknowledged?

As for the beginning of the text, I would say that Carleton developed the app (checking with Joe on wording). For the wording related to NCC (and the funders) I can check with NCC folks.

**Comment by ricschuster** [comment]
Here a draft English version:

"The Where To Work application was developed by Joe Bennett and his team at Carleton University under contract with the Nature Conservancy of Canada. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada."

The French version of this:

"L'application Where To Work (Où travailler)a été développée par Joe Bennett et son équipe de l'Université Carleton, sous contrat avec Conservation de la nature Canada. Ce travail a été soutenu par les généreuses contributions d'Environnement et Changement climatique Canada et de la Banque royale du Canada."

**Comment by jeffreyhanson** [comment]
Yeah, that sounds great! Maybe we could add my name and Jaimie's name somewhere - what do you think of the text below?

> The Where To Work application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University under contract with the Nature Conservancy of Canada. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

Also, to clarify, none of the web apps themselves have any French text (the French text is only found in the launcher at the moment) - so do you still want a French version in the acknowledgements tab for the WTW tool? It seems a bit out of place to have a single French paragraph in the tool - but I understand if this is important to include?

**Comment by ricschuster** [comment]
I like it. I'm a bit sad that I'm with the catch all NCC umbrella in there and not part of the gang, but that's okay.

The French version is essentially for record keeping here, I don't think adding the French text would make that much sense at this point.

**Comment by jeffreyhanson** [comment]
Yeah - I agree it's a shame you're name isn't there. I don't suppose we could tweak it like this or something?

> The Where To Work application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University. It was developed under contract with the Nature Conservancy of Canada, under the guidance of Richard Schuster. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

**Comment by jeffreyhanson** [comment]
Re French: ah ok - I'll see if I can include the French version in a commented out (or hidden) part of the text/app somewhere so it's not lost.

**Comment by ricschuster** [comment]
> The Where To Work application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University. It was developed under contract with the Nature Conservancy of Canada, under the guidance of Richard Schuster. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

I like it. Lets use that. Thanks!

**Comment by jeffreyhanson** [comment]
Just realized I used under twice, perhaps:

> The Where To Work application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University. It was developed under contract with the Nature Conservancy of Canada, with the guidance of Richard Schuster. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

Not sure if guidance is the right word though - I feel it doesn't quite reflect the huge amount of input you've had on this?

**Comment by ricschuster** [comment]
> The Where To Work application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University and Richard Schuster at the Nature Conservancy of Canada. The work by Carleton University was completed under contract with the Nature Conservancy of Canada. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

How about this? Its longer, but doesn't really matter I think.

**Comment by jeffreyhanson** [comment]
Yeah that looks great! I'll add that. Shall I use this (replacing the app name) for the WTD tool too?

**Comment by jeffreyhanson** [comment]
For reference the relevant file that needs to be changed is https://github.com/NCC-CNC/wheretowork/blob/master/inst/app/text/acknowledge-ncc.md

**Comment by ricschuster** [comment]
> Yeah that looks great! I'll add that. Shall we use this (replacing the app name) for the WTD tool too?

Yes please.

**Comment by jeffreyhanson** [comment]
Ok can do.
